using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class DashboardQueryServiceTests : BaseTest
{
    private DashboardQueryService _dashboardQueryService;

    private const string DashboardConfigFilePath = $"{nameof(DashboardQueryServiceTests)}_dashy_conf.yml";

    [SetUp]
    public void Setup()
    {
        File.WriteAllText(DashboardConfigFilePath, """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.example
                icon: hl-jellyfin
                tags:
                - _autogenerated
                - host=media-01
              - title: UserItem
                url: https://user.example
                icon: favicon-local
                tags:
                - host=user-host
            """);
        _dashboardQueryService = ServiceProvider.GetRequiredService<DashboardQueryService>();
    }

    [TearDown]
    public void TearDown()
    {
        if (File.Exists(DashboardConfigFilePath))
        {
            File.Delete(DashboardConfigFilePath);
        }
    }

    [Test]
    public async Task ListServices_RoundTripsAutogeneratedFlagAndHostname()
    {
        var services = await _dashboardQueryService.ListServices();

        Assert.That(services, Has.Count.EqualTo(2));

        var jellyfin = services.Single(s => s.Name == "Jellyfin");
        Assert.That(jellyfin.Autogenerated, Is.True);
        Assert.That(jellyfin.Hostname, Is.EqualTo("media-01"));
        Assert.That(jellyfin.Icon, Is.EqualTo("hl-jellyfin"));
        Assert.That(jellyfin.Category, Is.EqualTo("Media"));

        var userItem = services.Single(s => s.Name == "UserItem");
        Assert.That(userItem.Autogenerated, Is.False);
        Assert.That(userItem.Hostname, Is.EqualTo("user-host"));
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        var managerOptions = new ManagerOptions
        {
            DashboardManagerType = DashboardManagerType.Dashy,
            DashboardConfigFilePath = DashboardConfigFilePath,
        };
        services.AddTransient<IOptions<ManagerOptions>>(_ => Options.Create(managerOptions));
    }
}
