using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Dsm.Shared.Tests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Dsm.Managers.Tests.UnitTests;

public class DashyDashboardManagerTests : BaseTest
{
    private DashyDashboardManager _dashyDashboardManager = null!;
    private string _dashboardConfigPath = null!;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
        // DI is built per-test in SetUp so IOptions<ManagerOptions> picks up the per-test path.
    }

    [SetUp]
    public void Setup()
    {
        _dashboardConfigPath = Path.Combine(Path.GetTempPath(), $"dsm_dashy_{Guid.NewGuid():N}.yml");
        File.Copy(TestDataUtilities.GetTestDataPath("dashy_conf.yml"), _dashboardConfigPath, overwrite: true);

        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        _dashyDashboardManager = ServiceProvider.GetRequiredService<DashyDashboardManager>();
    }

    [TearDown]
    public void TearDown()
    {
        if (File.Exists(_dashboardConfigPath))
        {
            File.Delete(_dashboardConfigPath);
        }
    }

    [Test]
    public async Task ListServicesReturnsFixtureContents()
    {
        var services = await _dashyDashboardManager.ListServices();

        Assert.That(services, Is.Not.Empty);
        Assert.That(services.Select(s => s.Name), Does.Contain("Jellyfin"));
        var jellyfin = services.First(s => s.Name == "Jellyfin");
        Assert.That(jellyfin.Url, Is.EqualTo("https://jellyfin.omegaho.me"));
        Assert.That(jellyfin.Category, Is.EqualTo("Media"));
        Assert.That(jellyfin.Hostname, Is.EqualTo("media-01"));
        Assert.That(jellyfin.Autogenerated, Is.True);
    }

    [Test]
    public async Task WriteServicesPersistsToDashboardFile()
    {
        var services = new List<Service>()
        {
            new Service("flood", "https://flood.example.com", "Downloading", null, null, "nas-01", false, autogenerated: true)
        };

        await _dashyDashboardManager.WriteServices(services);

        var written = await File.ReadAllTextAsync(_dashboardConfigPath);
        Assert.That(written, Does.Contain("flood"));
        Assert.That(written, Does.Contain("https://flood.example.com"));
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardConfigFilePath = _dashboardConfigPath;
            opts.DashboardManagerType = DashboardManagerType.Dashy;
        });
    }
}
