using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class DashboardCommandProcessorTests : BaseTest
{
    private DashboardCommandProcessor _dashboardCommandProcessor;

    private const string DashboardConfigFilePath = $"{nameof(DashboardCommandProcessorTests)}_dashy_conf.yml";

    [SetUp]
    public void Setup()
    {
        File.WriteAllText(DashboardConfigFilePath, """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.old
                icon: favicon-local
                tags:
                - _autogenerated
                - host=host-1
              - title: MyCustomItem
                url: https://custom.example
                icon: favicon-local
                tags:
                - host=custom-host
            """);
        _dashboardCommandProcessor = ServiceProvider.GetRequiredService<DashboardCommandProcessor>();
    }

    [TearDown]
    public void TearDown()
    {
        if (File.Exists(DashboardConfigFilePath))
        {
            File.Delete(DashboardConfigFilePath);
        }
    }

    [Test]
    public async Task UpdateServicesTest_ReplacesAutogeneratedPreservesUserAddedAndWritesFile()
    {
        var services = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "Media", null, null, "host-1", false),
        };

        var combined = await _dashboardCommandProcessor.UpdateWithServicesFromProvider(services);

        var jellyfin = combined.SingleOrDefault(s => s.Name == "Jellyfin");
        Assert.That(jellyfin, Is.Not.Null);
        Assert.That(jellyfin!.Url, Is.EqualTo("https://jellyfin.new"));
        Assert.That(combined.Any(s => s.Name == "MyCustomItem"), Is.True,
            "User-added (non-autogenerated) item must survive the merge.");

        var writtenYaml = await File.ReadAllTextAsync(DashboardConfigFilePath);
        Assert.That(writtenYaml, Does.Contain("https://jellyfin.new"));
        Assert.That(writtenYaml, Does.Contain("MyCustomItem"));
        Assert.That(writtenYaml, Does.Not.Contain("https://jellyfin.old"));
    }

    [Test]
    public async Task UpdateServicesTest_SkipsIgnoredAndBlankUrlServices()
    {
        var services = new List<Service>
        {
            new Service("Ignored", "https://ignored.example", "Media", null, null, "h", ignore: true),
            new Service("Blank", "", "Media", null, null, "h", false),
            new Service("Included", "https://included.example", "Media", null, null, "h", false),
        };

        var combined = await _dashboardCommandProcessor.UpdateWithServicesFromProvider(services);

        Assert.That(combined.Any(s => s.Name == "Ignored"), Is.False);
        Assert.That(combined.Any(s => s.Name == "Blank"), Is.False);
        Assert.That(combined.Any(s => s.Name == "Included"), Is.True);
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        var managerOptions = new ManagerOptions
        {
            DashboardManagerType = DashboardManagerType.Dashy,
            DashboardConfigFilePath = DashboardConfigFilePath,
        };
        services.AddTransient<IOptions<ManagerOptions>>(_ => Options.Create(managerOptions));

        var defaultOptions = new ServiceDefaultOptions { UseWalkxcodeDashboardIcons = false };
        services.AddTransient<IOptions<ServiceDefaultOptions>>(_ => Options.Create(defaultOptions));
    }
}
