using Dsm.Managers.Configuration;
using Dsm.Managers.Factories;
using Dsm.Shared.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class ServiceFactoryTests : BaseTest
{
    private WithDefaultsServiceFactory _withDefaultsServiceFactory;

    public override void OneTimeSetUp()
    {
        base.OneTimeSetUp();
        _withDefaultsServiceFactory = ServiceProvider.GetRequiredService<WithDefaultsServiceFactory>();
    }

    [TestCase("Proxmox", "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox.png")]
    [TestCase("AdGuard Home", "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png")]
    [TestCase("Resilio Sync", "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/resiliosync.png")]
    [Category("Network")]
    public void WalkxcodeDashboardIcons_Test(string serviceName, string expectedImageUrl)
    {
        var service = new Service(serviceName, "https://example.com", null, null, null, null, false);
        var serviceWithDefaults = _withDefaultsServiceFactory.CreateWithDefaults(service);

        Assert.That(serviceWithDefaults.ImageUrl, Is.EqualTo(expectedImageUrl));
    }

    [Test]
    public void NameWithHostnameFormatString_IsApplied()
    {
        var service = new Service("Traefik", "https://example.com", null, null, null, "host1", false);

        var result = _withDefaultsServiceFactory.CreateWithDefaults(service);

        Assert.That(result.Name, Is.EqualTo("Traefik [host1]"));
    }

    [Test]
    public void RelativeImagePath_IsResolvedAgainstServiceUrl()
    {
        var service = new Service("Grafana", "https://grafana.example.com", null, null, null, "host1", false);

        var result = _withDefaultsServiceFactory.CreateWithDefaults(service);

        Assert.That(result.ImageUrl, Is.EqualTo("https://grafana.example.com/public/img/grafana_icon.svg"));
    }

    [Test]
    public void AbsoluteImagePath_PassesThroughUnchanged()
    {
        var service = new Service("Healthchecks", "https://healthchecks.example.com", null, null, null, "host1", false);

        var result = _withDefaultsServiceFactory.CreateWithDefaults(service);

        Assert.That(result.ImageUrl, Is.EqualTo("https://healthchecks.io/static/img/favicon.png"));
    }

    [Test]
    public void AutogeneratedFlag_IsPreserved()
    {
        var service = new Service("SomeService", "https://example.com", "media", null, null, "h", false, autogenerated: true);

        var result = _withDefaultsServiceFactory.CreateWithDefaults(service);

        Assert.That(result.Autogenerated, Is.True);
    }
}
