---
api_url: https://dashboard-services-manager.omegaho.me
dashy_config_file_path: /config/dashy_config.yaml
docker_label_prefix: dcm
are_service_hosts_https: true
ignored_service_names:
- Dashy
- Dashboard Services Manager Api
- Loki
section_icons:
  downloading: fas fa-download
  infrastructure: fas fa-chart-network
  media: fas fa-tv
  monitoring: fas fa-chart-line
  network: fas fa-network-wired
  smart home: fas fa-house-signal
  storage: fas fa-database
  uncategorized: fas fa-question
  utilities: fas fa-toolbox
default_service_configs:
  adguardhome:
    name_with_hostname_format_string: AdGuard Home [%s]
    category: network
    icon: hl-adguardhome
  adguardhome sync:
    name_with_hostname_format_string: AdGuard Home Sync
    category: utilities
    icon: hl-adguard-home
  changedetectionio:
    category: utilities
  flexget:
    category: downloading
    icon: hl-flexget
  flood:
    category: downloading
  gitea:
    category: storage
  grafana:
    category: monitoring
    image_path: /public/img/grafana_icon.svg
  healthchecks:
    category: monitoring
    image_path: https://healthchecks.io/static/img/favicon.png
  homeassistant:
    category: smart home
    image_path: /static/icons/favicon-apple-180x180.png
  homebridge:
    category: smart home
  minio:
    category: storage
    image_path: /favicon-96x96.png
  pikvm:
    category: infrastructure
    image_path: /share/apple-touch-icon.png
  plex:
    category: media
    icon: hl-plex
  prometheus:
    category: monitoring
    icon: hl-prometheus
  proxmox:
    category: infrastructure
    image_path: /pve2/images/logo-128.png
  scrutiny:
    category: monitoring
    icon: hl-scrutiny
  tautulli:
    category: media
  traefik:
    name_with_hostname_format_string: Traefik [%s]
    category: network
    image_path: /dashboard/statics/icons/favicon-96x96.png
  unifi:
    category: network
