version: "3.9"
services:
  dashboard-services-manager-api:
    container_name: dashboard-services-manager-api
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - DOCKER_GID=${DOCKER_GID}
    environment:
      - HOSTNAME=${HOSTNAME}
    ports:
    - 8080:8080
    volumes:
      - ./manager-config.yaml:/config/manager-config.yaml:ro
      # - /var/run/docker.sock:/var/run/docker.sock
  dashboard-services-manager-provider:
    container_name: dashboard-services-manager-provider
    build:
      context: .
      dockerfile: provider.Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - DOCKER_GID=${DOCKER_GID}
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - ./provider-config.yaml:/config/provider-config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock