using System.Collections.Concurrent;
using Dsm.Managers.Configuration;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Factories;

public class WithDefaultsServiceFactory
{
    public const string HttpClientName = "walkxcode";
    private const string BaseWalkxcodeDashboardIconUrl = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/";
    private static readonly TimeSpan NegativeCacheTtl = TimeSpan.FromHours(1);
    private static readonly ConcurrentDictionary<string, (string? Url, DateTime CachedAt)> WalkxcodeIconCache = new();

    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly IHttpClientFactory _httpClientFactory;

    public WithDefaultsServiceFactory(
        IOptions<ServiceDefaultOptions> defaultOptions,
        IHttpClientFactory httpClientFactory)
    {
        _serviceDefaultOptions = defaultOptions.Value;
        _httpClientFactory = httpClientFactory;
    }

    public async Task<Service> CreateWithDefaultsAsync(Service service)
    {
        _serviceDefaultOptions.Services.TryGetValue(service.Name, out var defaultServiceConfig);

        var name = ApplyNameFormat(service, defaultServiceConfig);
        var category = !string.IsNullOrEmpty(service.Category) ? service.Category : defaultServiceConfig?.Category;
        var icon = !string.IsNullOrEmpty(service.Icon) ? service.Icon : defaultServiceConfig?.Icon;
        var imagePath = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : defaultServiceConfig?.ImagePath;
        var imageUrl = ResolveImageUrl(imagePath, service.Url);

        if (_serviceDefaultOptions.UseWalkxcodeDashboardIcons &&
            string.IsNullOrEmpty(icon) &&
            string.IsNullOrEmpty(imageUrl))
        {
            imageUrl = await GetWalkxcodeDashboardIconUrlAsync(service.Name);
        }

        return new Service(
            name,
            service.Url,
            category,
            icon,
            imageUrl,
            service.Hostname,
            service.Ignore,
            service.Autogenerated);
    }

    private static string ApplyNameFormat(Service service, ServiceConfig? defaultServiceConfig)
    {
        var format = defaultServiceConfig?.NameWithHostnameFormatString;
        if (string.IsNullOrEmpty(format) || string.IsNullOrEmpty(service.Hostname))
        {
            return service.Name;
        }
        return format.Replace("%s", service.Hostname);
    }

    private static string? ResolveImageUrl(string? imagePath, string? serviceUrl)
    {
        if (string.IsNullOrEmpty(imagePath))
        {
            return null;
        }
        if (Uri.TryCreate(imagePath, UriKind.Absolute, out var absolute) &&
            (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps))
        {
            return absolute.ToString();
        }
        if (!string.IsNullOrEmpty(serviceUrl) &&
            Uri.TryCreate(serviceUrl, UriKind.Absolute, out var baseUri))
        {
            return new Uri(baseUri, imagePath).ToString();
        }
        return imagePath;
    }

    private async Task<string?> GetWalkxcodeDashboardIconUrlAsync(string serviceName)
    {
        if (WalkxcodeIconCache.TryGetValue(serviceName, out var cached) &&
            (cached.Url is not null || DateTime.UtcNow - cached.CachedAt < NegativeCacheTtl))
        {
            return cached.Url;
        }

        var lowerCaseServiceName = serviceName.ToLowerInvariant();
        var potentialIconNames = new[]
        {
            lowerCaseServiceName.Replace(" ", string.Empty),
            lowerCaseServiceName.Replace(" ", "-"),
            lowerCaseServiceName.Replace(".", "-")
        };

        var httpClient = _httpClientFactory.CreateClient(HttpClientName);
        foreach (var potentialIconName in potentialIconNames)
        {
            var walkxcodeDashboardIconUrl = $"{BaseWalkxcodeDashboardIconUrl}{potentialIconName}.png";
            using var request = new HttpRequestMessage(HttpMethod.Head, walkxcodeDashboardIconUrl);
            using var response = await httpClient.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                WalkxcodeIconCache[serviceName] = (walkxcodeDashboardIconUrl, DateTime.UtcNow);
                return walkxcodeDashboardIconUrl;
            }
        }

        WalkxcodeIconCache[serviceName] = (null, DateTime.UtcNow);
        return null;
    }
}
