using Dsm.Shared.Models;

namespace Dsm.Managers.Factories;

public class ServicesCombiner
{
    public List<Service> CombineExistingServicesWithNewServices(
        List<Service> existingServices,
        List<Service> newServices)
    {
        var newTitles = newServices
            .Select(s => s.Name)
            .ToHashSet();
        var newHostnames = newServices
            .Select(s => s.Hostname)
            .Where(h => !string.IsNullOrEmpty(h))
            .ToHashSet();

        var result = new List<Service>(newServices);
        foreach (var existing in existingServices)
        {
            var overlaps = newTitles.Contains(existing.Name) ||
                           (!string.IsNullOrEmpty(existing.Hostname) &&
                            newHostnames.Contains(existing.Hostname));
            if (!existing.Autogenerated || !overlaps)
            {
                result.Add(existing);
            }
        }

        return result
            .OrderBy(s => s.Category)
            .ThenBy(s => s.Name)
            .ToList();
    }
}
