using Dsm.Managers.Configuration;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Factories;

public class WithDefaultsServiceFactory
{
    private const string BaseWalkxcodeDashboardIconUrl = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/";
    private static HttpClient _walkxcodeDashboardIconHttpClient = new HttpClient();

    private readonly ServiceDefaultOptions _serviceDefaultOptions;

    public WithDefaultsServiceFactory(IOptions<ServiceDefaultOptions> defaultOptions)
    {
        _serviceDefaultOptions = defaultOptions.Value;
    }

    public Service CreateWithDefaults(Service service)
    {
        _serviceDefaultOptions.Services.TryGetValue(service.Name.ToLower(), out var defaultServiceConfig);

        var name = ApplyNameFormat(service, defaultServiceConfig);
        var category = !string.IsNullOrEmpty(service.Category) ? service.Category : defaultServiceConfig?.Category;
        var icon = !string.IsNullOrEmpty(service.Icon) ? service.Icon : defaultServiceConfig?.Icon;
        var imagePath = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : defaultServiceConfig?.ImagePath;
        var imageUrl = ResolveImageUrl(imagePath, service.Url);

        if (_serviceDefaultOptions.UseWalkxcodeDashboardIcons &&
            string.IsNullOrEmpty(icon) &&
            string.IsNullOrEmpty(imageUrl))
        {
            imageUrl = GetWalkxcodeDashboardIconUrl(service.Name);
        }

        return new Service(
            name,
            service.Url,
            category,
            icon,
            imageUrl,
            service.Hostname,
            service.Ignore,
            service.Autogenerated);
    }

    private static string ApplyNameFormat(Service service, ServiceConfig? defaultServiceConfig)
    {
        var format = defaultServiceConfig?.NameWithHostnameFormatString;
        if (string.IsNullOrEmpty(format) || string.IsNullOrEmpty(service.Hostname))
        {
            return service.Name;
        }
        return string.Format(format.Replace("%s", "{0}"), service.Hostname);
    }

    private static string? ResolveImageUrl(string? imagePath, string? serviceUrl)
    {
        if (string.IsNullOrEmpty(imagePath))
        {
            return null;
        }
        if (Uri.TryCreate(imagePath, UriKind.Absolute, out var absolute) &&
            (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps))
        {
            return absolute.ToString();
        }
        if (!string.IsNullOrEmpty(serviceUrl) &&
            Uri.TryCreate(serviceUrl, UriKind.Absolute, out var baseUri))
        {
            return new Uri(baseUri, imagePath).ToString();
        }
        return imagePath;
    }

    private static string? GetWalkxcodeDashboardIconUrl(string serviceName)
    {
        var lowerCaseServiceName = serviceName.ToLower();
        var potentialIconNames = new[]
        {
            lowerCaseServiceName.Replace(" ", string.Empty),
            lowerCaseServiceName.Replace(" ", "-"),
            lowerCaseServiceName.Replace(".", "-")
        };

        foreach (var potentialIconName in potentialIconNames)
        {
            var walkxcodeDashboardIconUrl = $"{BaseWalkxcodeDashboardIconUrl}{potentialIconName}.png";
            var request = new HttpRequestMessage(HttpMethod.Head, walkxcodeDashboardIconUrl);
            var response = _walkxcodeDashboardIconHttpClient.Send(request);
            if (response.IsSuccessStatusCode)
            {
                return walkxcodeDashboardIconUrl;
            }
        }

        return null;
    }
}
