using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Dsm.Shared.Tests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class DashyDashboardManagerTests : BaseTest
{
    private DashyDashboardManager _dashyDashboardManager = null!;
    private string _dashboardConfigPath = null!;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
        // DI is built per-test in SetUp so the DashboardManagerConfig picks up the per-test path.
    }

    [SetUp]
    public void Setup()
    {
        _dashboardConfigPath = Path.Combine(Path.GetTempPath(), $"dsm_dashy_{Guid.NewGuid():N}.yml");
        File.Copy(TestDataUtilities.GetTestDataPath("dashy_conf.yml"), _dashboardConfigPath, overwrite: true);

        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        _dashyDashboardManager = (DashyDashboardManager)factory.Create(config);
    }

    [TearDown]
    public void TearDown()
    {
        if (File.Exists(_dashboardConfigPath))
        {
            File.Delete(_dashboardConfigPath);
        }
    }

    [Test]
    public async Task ListServicesReturnsFixtureContents()
    {
        var services = await _dashyDashboardManager.ListServices();

        Assert.That(services, Is.Not.Empty);
        Assert.That(services.Select(s => s.Name), Does.Contain("Jellyfin"));
        var jellyfin = services.First(s => s.Name == "Jellyfin");
        Assert.That(jellyfin.Url, Is.EqualTo("https://jellyfin.omegaho.me"));
        Assert.That(jellyfin.Category, Is.EqualTo("Media"));
        Assert.That(jellyfin.Hostname, Is.EqualTo("media-01"));
        Assert.That(jellyfin.Autogenerated, Is.True);
    }

    [Test]
    public async Task WriteServicesRoundTripsThroughListServices()
    {
        var services = new List<Service>()
        {
            new Service("flood", "https://flood.example.com", "Downloading", null, null, "nas-01", false, autogenerated: true)
        };

        await _dashyDashboardManager.WriteServices(services);

        var roundTripped = await _dashyDashboardManager.ListServices();
        var flood = roundTripped.Single(s => s.Name == "flood");
        Assert.That(flood.Url, Is.EqualTo("https://flood.example.com"));
        Assert.That(flood.Category, Is.EqualTo("Downloading"));
        Assert.That(flood.Hostname, Is.EqualTo("nas-01"));
        Assert.That(flood.Autogenerated, Is.True);
    }

    [Test]
    public async Task WriteServicesPreservesAutogeneratedFlagPerService()
    {
        var userEntry = new Service(
            "hand-written", "https://user.example.com", "Links",
            "mdi-star", null, null, false, autogenerated: false);
        var autoEntry = new Service(
            "auto", "https://auto.example.com", "Media",
            "mdi-robot", null, "media-01", false, autogenerated: true);

        await _dashyDashboardManager.WriteServices(new List<Service> { userEntry, autoEntry });

        var roundTripped = await _dashyDashboardManager.ListServices();
        Assert.Multiple(() =>
        {
            Assert.That(roundTripped.Single(s => s.Name == "hand-written").Autogenerated, Is.False);
            Assert.That(roundTripped.Single(s => s.Name == "auto").Autogenerated, Is.True);
        });
    }

    [Test]
    public async Task ListServices_ReturnsEmpty_WhenConfigFileMissing()
    {
        File.Delete(_dashboardConfigPath);

        var services = await _dashyDashboardManager.ListServices();

        Assert.That(services, Is.Empty);
    }

    [Test]
    public async Task WriteServicesDoesNotEmitHostTagWhenHostnameIsNull()
    {
        var service = new Service(
            "no-host", "https://no-host.example.com", "Links",
            null, null, null, false, autogenerated: true);

        await _dashyDashboardManager.WriteServices(new List<Service> { service });

        var roundTripped = await _dashyDashboardManager.ListServices();
        Assert.That(roundTripped.Single(s => s.Name == "no-host").Hostname, Is.Null);
    }

    private DashyDashboardManager CreateManagerWithStatusMonitoring(bool enabled)
    {
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        return (DashyDashboardManager)factory.Create(new DashboardManagerConfig
        {
            DashboardManagerType = DashboardManagerType.Dashy,
            DashboardConfigFilePath = _dashboardConfigPath,
            EnableStatusMonitoring = enabled
        });
    }

    [Test]
    public async Task EnableStatusMonitoring_True_EmitsStatusCheckOnEveryItem()
    {
        File.Delete(_dashboardConfigPath);
        var manager = CreateManagerWithStatusMonitoring(true);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
            new("Grafana",  "https://grafana.example",  "Monitoring", null, null, "mon-01",   false, autogenerated: true),
        };

        await manager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_dashboardConfigPath);

        var statusCheckCount = written.Split("statusCheck: true").Length - 1;
        Assert.That(statusCheckCount, Is.EqualTo(services.Count));
    }

    [Test]
    public async Task EnableStatusMonitoring_False_OmitsStatusCheck()
    {
        File.Delete(_dashboardConfigPath);
        var manager = CreateManagerWithStatusMonitoring(false);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_dashboardConfigPath);

        Assert.That(written, Does.Not.Contain("statusCheck"));
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Dashy,
                    DashboardConfigFilePath = _dashboardConfigPath,
                },
            };
        });
    }
}
