using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Managers.HostBuilder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class DashboardQueryServiceTests : PerTestHostedTestBase
{
    [Test]
    public async Task ListServices_RoundTripsAutogeneratedFlagAndHostname()
    {
        using var dashyDir = TestTempDir.Create("dsm_qs");
        File.WriteAllText(dashyDir.RootedPath(DashyDashboardManager.ConfigFileName), """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.example
                icon: hl-jellyfin
                tags:
                - _autogenerated
                - host=media-01
              - title: UserItem
                url: https://user.example
                icon: favicon-local
                tags:
                - host=user-host
            """);

        var queryService = BuildQueryService((DashboardManagerType.Dashy, dashyDir.Path));

        var services = await queryService.ListServices();

        Assert.That(services, Has.Count.EqualTo(2));
        var jellyfin = services.Single(s => s.Name == "Jellyfin");
        Assert.That(jellyfin.Autogenerated, Is.True);
        Assert.That(jellyfin.Hostname, Is.EqualTo("media-01"));
        Assert.That(jellyfin.Icon, Is.EqualTo("hl-jellyfin"));
        Assert.That(jellyfin.Category, Is.EqualTo("Media"));

        var userItem = services.Single(s => s.Name == "UserItem");
        Assert.That(userItem.Autogenerated, Is.False);
        Assert.That(userItem.Hostname, Is.EqualTo("user-host"));
    }

    [Test]
    public async Task ListServices_DedupesAcrossManagersByNameAndHostname_FirstWins()
    {
        using var dashyDir = TestTempDir.Create("dsm_qs_dashy");
        using var homepageDir = TestTempDir.Create("dsm_qs_hp");

        // Dashy: Jellyfin@media-01 + DashyOnly@media-01
        File.WriteAllText(dashyDir.RootedPath(DashyDashboardManager.ConfigFileName), """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.dashy
                icon: hl-jellyfin
                tags:
                - host=media-01
              - title: DashyOnly
                url: https://dashy-only.example
                icon: favicon-local
                tags:
                - host=media-01
            """);

        // Homepage: Jellyfin@media-01 (deduped — Dashy wins) + HomepageOnly@media-01
        File.WriteAllText(homepageDir.RootedPath(HomepageDashboardManager.ServicesFileName), """
            - Media:
                - Jellyfin:
                    href: https://jellyfin.homepage
                    server: media-01
                - HomepageOnly:
                    href: https://hp-only.example
                    server: media-01
            """);

        var queryService = BuildQueryService(
            (DashboardManagerType.Dashy, dashyDir.Path),
            (DashboardManagerType.Homepage, homepageDir.Path));

        var services = await queryService.ListServices();

        var jellyfinMatches = services.Where(s => s.Name == "Jellyfin").ToList();
        Assert.That(jellyfinMatches, Has.Count.EqualTo(1), "(Name, Hostname) collision should dedupe");
        Assert.That(jellyfinMatches[0].Url, Is.EqualTo("https://jellyfin.dashy"),
            "First manager (Dashy) wins on conflict");

        Assert.That(services.Any(s => s.Name == "DashyOnly"), Is.True);
        Assert.That(services.Any(s => s.Name == "HomepageOnly"), Is.True,
            "Entries unique to later managers still survive");
    }

    private DashboardQueryService BuildQueryService(params (DashboardManagerType Type, string Path)[] managers)
    {
        var managerConfigs = managers
            .Select(m => new DashboardManagerConfig
            {
                DashboardManagerType = m.Type,
                DashboardConfigDirectoryPath = m.Path,
            })
            .ToList();

        var host = CreateHost(configureServices: services =>
        {
            services.AddDsmManagerServices();
            services.AddTransient<IOptions<ManagerOptions>>(_ =>
                Options.Create(new ManagerOptions { DashboardManagers = managerConfigs }));
            services.AddTransient<IOptions<ServiceDefaultOptions>>(_ =>
                Options.Create(new ServiceDefaultOptions()));
        });
        return host.Services.GetRequiredService<DashboardQueryService>();
    }
}
