using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class DashboardQueryServiceTests : BaseTest
{
    private DashboardQueryService _dashboardQueryService;

    private const string DashboardConfigDir = $"{nameof(DashboardQueryServiceTests)}_dashy";
    private static readonly string DashboardConfigFilePath = Path.Combine(DashboardConfigDir, DashyDashboardManager.ConfigFileName);

    [SetUp]
    public void Setup()
    {
        Directory.CreateDirectory(DashboardConfigDir);
        File.WriteAllText(DashboardConfigFilePath, """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.example
                icon: hl-jellyfin
                tags:
                - _autogenerated
                - host=media-01
              - title: UserItem
                url: https://user.example
                icon: favicon-local
                tags:
                - host=user-host
            """);
        _dashboardQueryService = ServiceProvider.GetRequiredService<DashboardQueryService>();
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(DashboardConfigDir))
        {
            Directory.Delete(DashboardConfigDir, recursive: true);
        }
    }

    [Test]
    public async Task ListServices_RoundTripsAutogeneratedFlagAndHostname()
    {
        var services = await _dashboardQueryService.ListServices();

        Assert.That(services, Has.Count.EqualTo(2));

        var jellyfin = services.Single(s => s.Name == "Jellyfin");
        Assert.That(jellyfin.Autogenerated, Is.True);
        Assert.That(jellyfin.Hostname, Is.EqualTo("media-01"));
        Assert.That(jellyfin.Icon, Is.EqualTo("hl-jellyfin"));
        Assert.That(jellyfin.Category, Is.EqualTo("Media"));

        var userItem = services.Single(s => s.Name == "UserItem");
        Assert.That(userItem.Autogenerated, Is.False);
        Assert.That(userItem.Hostname, Is.EqualTo("user-host"));
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        var managerOptions = new ManagerOptions
        {
            DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Dashy,
                    DashboardConfigDirectoryPath = DashboardConfigDir,
                },
            },
        };
        services.AddTransient<IOptions<ManagerOptions>>(_ => Options.Create(managerOptions));
    }
}
