using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Managers.HostBuilder;
using Dsm.Shared.Models;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class DashboardCommandProcessorTests : PerTestHostedTestBase
{
    [Test]
    public async Task UpdateServicesTest_ReplacesAutogeneratedPreservesUserAddedAndWritesFile()
    {
        using var dashyDir = TestTempDir.Create("dsm_cp_replace");
        var dashyPath = dashyDir.RootedPath(DashyDashboardManager.ConfigFileName);
        File.WriteAllText(dashyPath, """
            ---
            sections:
            - name: Media
              items:
              - title: Jellyfin
                url: https://jellyfin.old
                icon: favicon-local
                tags:
                - _autogenerated
                - host=host-1
              - title: MyCustomItem
                url: https://custom.example
                icon: favicon-local
                tags:
                - host=custom-host
            """);

        var processor = BuildProcessor((DashboardManagerType.Dashy, dashyDir.Path));

        var services = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "Media", null, null, "host-1", false),
        };

        var response = await processor.UpdateWithServicesFromProvider(services);

        var dashyResult = response["Dashy"];
        var jellyfin = dashyResult.SingleOrDefault(s => s.Name == "Jellyfin");
        Assert.That(jellyfin, Is.Not.Null);
        Assert.That(jellyfin!.Url, Is.EqualTo("https://jellyfin.new"));
        Assert.That(dashyResult.Any(s => s.Name == "MyCustomItem"), Is.True,
            "User-added (non-autogenerated) item must survive the merge.");

        var writtenYaml = await File.ReadAllTextAsync(dashyPath);
        Assert.That(writtenYaml, Does.Contain("https://jellyfin.new"));
        Assert.That(writtenYaml, Does.Contain("MyCustomItem"));
        Assert.That(writtenYaml, Does.Not.Contain("https://jellyfin.old"));
    }

    [Test]
    public async Task UpdateServicesTest_SkipsIgnoredAndBlankUrlServices()
    {
        using var dashyDir = TestTempDir.Create("dsm_cp_skip");
        File.WriteAllText(dashyDir.RootedPath(DashyDashboardManager.ConfigFileName), """
            ---
            sections:
            - name: Media
              items: []
            """);

        var processor = BuildProcessor((DashboardManagerType.Dashy, dashyDir.Path));

        var services = new List<Service>
        {
            new Service("Ignored", "https://ignored.example", "Media", null, null, "h", ignore: true),
            new Service("Blank", "", "Media", null, null, "h", false),
            new Service("Included", "https://included.example", "Media", null, null, "h", false),
        };

        var response = await processor.UpdateWithServicesFromProvider(services);
        var dashyResult = response["Dashy"];

        Assert.That(dashyResult.Any(s => s.Name == "Ignored"), Is.False);
        Assert.That(dashyResult.Any(s => s.Name == "Blank"), Is.False);
        Assert.That(dashyResult.Any(s => s.Name == "Included"), Is.True);
    }

    [Test]
    public async Task FansOutToBothManagersAndPreservesEachDashboardsHandEntries()
    {
        using var dashyDir = TestTempDir.Create("dsm_cp_fanout_dashy");
        using var homepageDir = TestTempDir.Create("dsm_cp_fanout_hp");
        var dashyPath = dashyDir.RootedPath(DashyDashboardManager.ConfigFileName);
        var homepagePath = homepageDir.RootedPath(HomepageDashboardManager.ServicesFileName);

        File.WriteAllText(dashyPath, """
            ---
            sections:
            - name: Existing
              items:
              - title: HandWrittenDashyEntry
                url: https://hand.example
                icon: favicon-local
                tags:
                - host=elsewhere
            """);

        File.WriteAllText(homepagePath, """
            - Existing:
                - HandWrittenHomepageEntry:
                    href: https://hand-hp.example
                    server: elsewhere
            """);

        var processor = BuildProcessor(
            (DashboardManagerType.Dashy, dashyDir.Path),
            (DashboardManagerType.Homepage, homepageDir.Path));

        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "Media", null, null, "host-1", false),
        };

        var response = await processor.UpdateWithServicesFromProvider(incoming);

        Assert.Multiple(() =>
        {
            Assert.That(response.Keys, Is.EquivalentTo(new[] { "Dashy", "Homepage" }));
            Assert.That(response["Dashy"].Any(s => s.Name == "Jellyfin"), Is.True);
            Assert.That(response["Dashy"].Any(s => s.Name == "HandWrittenDashyEntry"), Is.True,
                "Dashy's hand-written entry survives in Dashy");
            Assert.That(response["Dashy"].Any(s => s.Name == "HandWrittenHomepageEntry"), Is.False,
                "Homepage's hand-written entry does not leak into Dashy");
            Assert.That(response["Homepage"].Any(s => s.Name == "Jellyfin"), Is.True);
            Assert.That(response["Homepage"].Any(s => s.Name == "HandWrittenHomepageEntry"), Is.True,
                "Homepage's hand-written entry survives in Homepage");
            Assert.That(response["Homepage"].Any(s => s.Name == "HandWrittenDashyEntry"), Is.False,
                "Dashy's hand-written entry does not leak into Homepage");
        });

        var dashyYaml = await File.ReadAllTextAsync(dashyPath);
        var homepageYaml = await File.ReadAllTextAsync(homepagePath);
        Assert.Multiple(() =>
        {
            Assert.That(dashyYaml, Does.Contain("https://jellyfin.new"));
            Assert.That(dashyYaml, Does.Contain("HandWrittenDashyEntry"));
            Assert.That(homepageYaml, Does.Contain("https://jellyfin.new"));
            Assert.That(homepageYaml, Does.Contain("HandWrittenHomepageEntry"));
        });
    }

    private DashboardCommandProcessor BuildProcessor(params (DashboardManagerType Type, string Path)[] managers)
    {
        var managerConfigs = managers
            .Select(m => new DashboardManagerConfig
            {
                DashboardManagerType = m.Type,
                DashboardConfigDirectoryPath = m.Path,
            })
            .ToList();

        var host = CreateHost(configureServices: services =>
        {
            services.AddDsmManagerServices();
            services.AddTransient<IOptions<ManagerOptions>>(_ =>
                Options.Create(new ManagerOptions { DashboardManagers = managerConfigs }));
            services.AddTransient<IOptions<ServiceDefaultOptions>>(_ =>
                Options.Create(new ServiceDefaultOptions()));
        });
        return host.Services.GetRequiredService<DashboardCommandProcessor>();
    }
}
