using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class HomepageDashboardManagerWidgetMatchingTests : BaseTest
{
    private TestTempDir _tempDir = null!;
    private string _homepageServicesPath = null!;
    private string? _widgetsPath;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
    }

    [SetUp]
    public void Setup()
    {
        _tempDir = TestTempDir.Create("dsm_homepage_widget_match");
        _homepageServicesPath = _tempDir.RootedPath(HomepageDashboardManager.ServicesFileName);
        _widgetsPath = null;
    }

    [TearDown]
    public void TearDown() => _tempDir.Dispose();

    private HomepageDashboardManager CreateManager()
    {
        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        return (HomepageDashboardManager)factory.Create(config);
    }

    private void WriteWidgetsFile(string yaml)
    {
        _widgetsPath = _tempDir.RootedPath("widgets.yaml");
        File.WriteAllText(_widgetsPath, yaml);
    }

    [Test]
    public async Task SingleWidget_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host.or.ip
                  key: apikey
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widget:"));
            Assert.That(written, Does.Contain("type: emby"));
            Assert.That(written, Does.Contain("key: apikey"));
            Assert.That(written, Does.Not.Contain("widgets:"));
        });
    }

    [Test]
    public async Task WidgetsList_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Sonarr:
                widgets:
                  - type: sonarr
                    url: http://sonarr.host
                    key: aaa
                  - type: uptimekuma
                    url: http://uptime.host
                    slug: status
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Sonarr", "https://sonarr.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: sonarr"));
            Assert.That(written, Does.Contain("type: uptimekuma"));
            Assert.That(written, Does.Contain("slug: status"));
        });
    }

    [Test]
    public async Task WidgetMatch_IsCaseInsensitive()
    {
        WriteWidgetsFile("""
            - emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("type: emby"));
    }

    [Test]
    public async Task ServiceWithoutMatchingWidget_GetsNoWidgetBlock()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task MissingWidgetsFile_DoesNotThrow_AndProducesNoWidgets()
    {
        _widgetsPath = _tempDir.RootedPath("does-not-exist.yaml");
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task NullWidgetsPath_DoesNotLoad()
    {
        _widgetsPath = null;
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task WidgetMatch_FallsBackToServiceDefaultsName_WhenNameWasReformatted()
    {
        WriteWidgetsFile("""
            - adguardhome:
                widget:
                  type: adguard
                  url: https://adguardhome.example
                  username: u
                  password: p
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://adguardhome.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widget:"));
            Assert.That(written, Does.Contain("type: adguard"));
            Assert.That(written, Does.Contain("username: u"));
        });
    }

    [Test]
    public async Task WidgetMatch_PrefersNameOverServiceDefaultsName()
    {
        WriteWidgetsFile("""
            - AdGuard Home (network-01):
                widget:
                  type: adguard
                  url: https://host-specific.example
            - adguardhome:
                widget:
                  type: adguard
                  url: https://fallback.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://adguardhome.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://host-specific.example"));
            Assert.That(written, Does.Not.Contain("url: https://fallback.example"));
        });
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Homepage,
                    DashboardConfigDirectoryPath = _tempDir.Path,
                    SourceHomepageServiceWidgetsFilePath = _widgetsPath,
                },
            };
        });
    }
}
