using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Dsm.Shared.Tests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class HomepageDashboardManagerWidgetsTests : BaseTest
{
    private string _homepageServicesDir = null!;
    private string _homepageServicesPath = null!;
    private string? _widgetsPath;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
    }

    [SetUp]
    public void Setup()
    {
        _homepageServicesDir = Path.Combine(Path.GetTempPath(), $"dsm_homepage_widgets_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_homepageServicesDir);
        _homepageServicesPath = Path.Combine(_homepageServicesDir, HomepageDashboardManager.ServicesFileName);
        _widgetsPath = null;
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_homepageServicesDir))
        {
            Directory.Delete(_homepageServicesDir, recursive: true);
        }
    }

    private HomepageDashboardManager CreateManager()
    {
        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        return (HomepageDashboardManager)factory.Create(config);
    }

    private void WriteWidgetsFile(string yaml)
    {
        _widgetsPath = Path.Combine(_homepageServicesDir, "widgets.yaml");
        File.WriteAllText(_widgetsPath, yaml);
    }

    [Test]
    public async Task SingleWidget_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host.or.ip
                  key: apikey
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widget:"));
            Assert.That(written, Does.Contain("type: emby"));
            Assert.That(written, Does.Contain("key: apikey"));
            Assert.That(written, Does.Not.Contain("widgets:"));
        });
    }

    [Test]
    public async Task WidgetsList_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Sonarr:
                widgets:
                  - type: sonarr
                    url: http://sonarr.host
                    key: aaa
                  - type: uptimekuma
                    url: http://uptime.host
                    slug: status
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Sonarr", "https://sonarr.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: sonarr"));
            Assert.That(written, Does.Contain("type: uptimekuma"));
            Assert.That(written, Does.Contain("slug: status"));
        });
    }

    [Test]
    public async Task WidgetMatch_IsCaseInsensitive()
    {
        WriteWidgetsFile("""
            - emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("type: emby"));
    }

    [Test]
    public async Task ServiceWithoutMatchingWidget_GetsNoWidgetBlock()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task MissingWidgetsFile_DoesNotThrow_AndProducesNoWidgets()
    {
        _widgetsPath = Path.Combine(_homepageServicesDir, "does-not-exist.yaml");
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task NullWidgetsPath_DoesNotLoad()
    {
        _widgetsPath = null;
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task WidgetMatch_FallsBackToServiceDefaultsName_WhenNameWasReformatted()
    {
        WriteWidgetsFile("""
            - adguardhome:
                widget:
                  type: adguard
                  url: https://adguardhome.example
                  username: u
                  password: p
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://adguardhome.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widget:"));
            Assert.That(written, Does.Contain("type: adguard"));
            Assert.That(written, Does.Contain("username: u"));
        });
    }

    [Test]
    public async Task WidgetMatch_PrefersNameOverServiceDefaultsName()
    {
        WriteWidgetsFile("""
            - AdGuard Home (network-01):
                widget:
                  type: adguard
                  url: https://host-specific.example
            - adguardhome:
                widget:
                  type: adguard
                  url: https://fallback.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://adguardhome.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://host-specific.example"));
            Assert.That(written, Does.Not.Contain("url: https://fallback.example"));
        });
    }

    [Test]
    public async Task MultipleEntriesSameName_DifferentServer_EachMatchesCorrectService()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://adguardhome.example
            - adguardhome:
                server: pi-rack
                widget:
                  type: adguard
                  url: https://adguardhome-02.example
            - adguardhome:
                server: network-03
                widget:
                  type: adguard
                  url: https://adguardhome-03.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag01.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (pi-rack)", "https://ag02.example", "Network", null, null, "pi-rack", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (network-03)", "https://ag03.example", "Network", null, null, "network-03", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://adguardhome.example"));
            Assert.That(written, Does.Contain("url: https://adguardhome-02.example"));
            Assert.That(written, Does.Contain("url: https://adguardhome-03.example"));
        });
    }

    [Test]
    public async Task ServerMatch_BeatsUnscopedEntry()
    {
        WriteWidgetsFile("""
            - adguardhome:
                widget:
                  type: adguard
                  url: https://unscoped.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://scoped.example"));
            Assert.That(written, Does.Not.Contain("url: https://unscoped.example"));
        });
    }

    [Test]
    public async Task UnscopedFallback_Used_WhenHostnameDoesNotMatchAnyServerScopedEntry()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: other-host
                widget:
                  type: adguard
                  url: https://other.example
            - adguardhome:
                widget:
                  type: adguard
                  url: https://fallback.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://fallback.example"));
            Assert.That(written, Does.Not.Contain("url: https://other.example"));
        });
    }

    [Test]
    public async Task NoMatch_WhenAllEntriesAreServerScopedAndNoneMatch()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: other-host
                widget:
                  type: adguard
                  url: https://other.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget:"));
    }

    [Test]
    public async Task ServerMatch_IsCaseInsensitive()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: Network-01
                widget:
                  type: adguard
                  url: https://scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("url: https://scoped.example"));
    }

    [Test]
    public async Task ServerMatchOnServiceDefaultsName_BeatsUnscopedNameMatch()
    {
        WriteWidgetsFile("""
            - AdGuard Home (network-01):
                widget:
                  type: adguard
                  url: https://name-unscoped.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://defaults-scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://defaults-scoped.example"));
            Assert.That(written, Does.Not.Contain("url: https://name-unscoped.example"));
        });
    }

    [Test]
    public async Task DuplicateEntry_SameNameAndServer_LastWins()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://first.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://second.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://second.example"));
            Assert.That(written, Does.Not.Contain("url: https://first.example"));
        });
    }

    [Test]
    public async Task WidgetMatch_SurvivesRoundTrip_AcrossMultipleHosts()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://ag-01.example
            - adguardhome:
                server: pi-rack
                widget:
                  type: adguard
                  url: https://ag-02.example
            - adguardhome:
                server: network-03
                widget:
                  type: adguard
                  url: https://ag-03.example
            """);
        var manager = CreateManager();

        var initial = new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag01.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (pi-rack)", "https://ag02.example", "Network", null, null, "pi-rack", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (network-03)", "https://ag03.example", "Network", null, null, "network-03", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        };
        await manager.WriteServices(initial);

        var firstWrite = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(firstWrite, Does.Contain("url: https://ag-01.example"));
            Assert.That(firstWrite, Does.Contain("url: https://ag-02.example"));
            Assert.That(firstWrite, Does.Contain("url: https://ag-03.example"));
        });

        var listed = await manager.ListServices();
        Assert.That(listed, Has.Count.EqualTo(3));
        Assert.That(listed.All(s => s.ServiceDefaultsName == "Adguardhome"), Is.True);

        await manager.WriteServices(listed);

        var secondWrite = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(secondWrite, Does.Contain("url: https://ag-01.example"));
            Assert.That(secondWrite, Does.Contain("url: https://ag-02.example"));
            Assert.That(secondWrite, Does.Contain("url: https://ag-03.example"));
        });
    }

    [Test]
    public async Task SiteMonitor_IsOmitted_ForServiceWithWidget_WhenStatusMonitoringEnabled()
    {
        WriteWidgetsFile("""
            - Sonarr:
                widget:
                  type: sonarr
                  url: http://sonarr.host
                  key: k
            """);

        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var manager = (HomepageDashboardManager)factory.Create(new DashboardManagerConfig
        {
            DashboardManagerType = DashboardManagerType.Homepage,
            DashboardConfigDirectoryPath = _homepageServicesDir,
            SourceHomepageServiceWidgetsFilePath = _widgetsPath,
            EnableStatusMonitoring = true,
        });

        await manager.WriteServices(new List<Service>
        {
            new("Sonarr",   "https://sonarr.example",   "Media", null, null, "media-01", false, autogenerated: true),
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("siteMonitor: https://jellyfin.example"));
            Assert.That(written, Does.Not.Contain("siteMonitor: https://sonarr.example"));
        });
    }

    [Test]
    public async Task BothWidgetAndWidgets_PrefersWidgets()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: single
                  url: http://single
                widgets:
                  - type: listed
                    url: http://listed
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: listed"));
            Assert.That(written, Does.Not.Contain("type: single"));
        });
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Homepage,
                    DashboardConfigDirectoryPath = _homepageServicesDir,
                    SourceHomepageServiceWidgetsFilePath = _widgetsPath,
                },
            };
        });
    }
}
