using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Managers.Services;
using Dsm.Managers.Services.IconSources;
using Dsm.Shared.Models;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Dsm.Managers.Tests.UnitTests;

[TestFixture]
[CancelAfter(TestTimeouts.HungThresholdMs)]
public class HomepageSettingsLayoutTests
{
    private string _dir = null!;
    private string _servicesPath = null!;
    private string _settingsPath = null!;

    [SetUp]
    public void Setup()
    {
        _dir = Path.Combine(Path.GetTempPath(), $"dsm_hp_settings_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_dir);
        _servicesPath = Path.Combine(_dir, HomepageDashboardManager.ServicesFileName);
        _settingsPath = Path.Combine(_dir, HomepageDashboardManager.SettingsFileName);
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_dir)) Directory.Delete(_dir, recursive: true);
    }

    private HomepageDashboardManager CreateManager(
        Dictionary<string, CategoryConfig>? categories = null,
        IEnumerable<IDashboardIconSource>? iconSources = null)
    {
        var options = Options.Create(new ServiceDefaultOptions
        {
            Categories = new Dictionary<string, CategoryConfig>(
                categories ?? new Dictionary<string, CategoryConfig>(), StringComparer.OrdinalIgnoreCase)
        });
        var iconResolver = new IconResolver(options, iconSources ?? Array.Empty<IDashboardIconSource>());
        return new HomepageDashboardManager(
            new DashboardManagerConfig
            {
                DashboardManagerType = DashboardManagerType.Homepage,
                DashboardConfigDirectoryPath = _dir
            },
            options,
            iconResolver,
            NullLogger<HomepageDashboardManager>.Instance);
    }

    private sealed class StubIconSource : IDashboardIconSource
    {
        public StubIconSource(DashboardIconSourceType type, string prefix)
        {
            Type = type;
            Prefix = prefix;
        }
        public DashboardIconSourceType Type { get; }
        public string Prefix { get; }
        public Task<(string? Url, string? MatchedName)> GetIconUrl(string iconName) =>
            throw new InvalidOperationException("Native pass-through must not invoke the CDN probe.");
    }

    private static Dictionary<object, object> ParseYamlFile(string path)
    {
        var text = File.ReadAllText(path);
        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();
        return deserializer.Deserialize<Dictionary<object, object>>(text) ?? new();
    }

    private static IDictionary<object, object> GetLayout(Dictionary<object, object> settings) =>
        (IDictionary<object, object>)settings["layout"];

    private static IDictionary<object, object> GetEntry(IDictionary<object, object> layout, string name) =>
        (IDictionary<object, object>)layout[name];

    [Test]
    public async Task WriteServices_CreatesSettingsYamlWhenMissing()
    {
        var manager = CreateManager(new()
        {
            ["Media"] = new CategoryConfig { Icon = "mdi-multimedia" }
        });
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        Assert.That(File.Exists(_settingsPath), Is.True);
        var settings = ParseYamlFile(_settingsPath);
        Assert.That(GetEntry(GetLayout(settings), "Media")["icon"], Is.EqualTo("mdi-multimedia"));
    }

    [Test]
    public async Task WriteServices_PreservesExistingTopLevelKeys()
    {
        await File.WriteAllTextAsync(_settingsPath, """
            theme: dark
            providers:
              longhorn:
                url: http://longhorn.example
            """);
        var manager = CreateManager(new()
        {
            ["Media"] = new CategoryConfig { Icon = "mdi-multimedia" }
        });
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        var settings = ParseYamlFile(_settingsPath);
        Assert.Multiple(() =>
        {
            Assert.That(settings["theme"], Is.EqualTo("dark"));
            Assert.That(settings, Contains.Key("providers"));
            Assert.That(GetEntry(GetLayout(settings), "Media")["icon"], Is.EqualTo("mdi-multimedia"));
        });
    }

    [Test]
    public async Task WriteServices_PreservesExistingLayoutSiblingsWhileUpdatingIcon()
    {
        await File.WriteAllTextAsync(_settingsPath, """
            layout:
              Media:
                icon: old-icon
                style: row
                columns: 4
            """);
        var manager = CreateManager(new()
        {
            ["Media"] = new CategoryConfig { Icon = "mdi-multimedia" }
        });
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        var entry = GetEntry(GetLayout(ParseYamlFile(_settingsPath)), "Media");
        Assert.Multiple(() =>
        {
            Assert.That(entry["icon"], Is.EqualTo("mdi-multimedia"));
            Assert.That(entry["style"], Is.EqualTo("row"));
            Assert.That(entry["columns"], Is.EqualTo("4"));
        });
    }

    [Test]
    public async Task WriteServices_DoesNotTouchLayoutEntriesForOtherCategories()
    {
        await File.WriteAllTextAsync(_settingsPath, """
            layout:
              Custom:
                icon: user-custom
                style: column
            """);
        var manager = CreateManager(new()
        {
            ["Media"] = new CategoryConfig { Icon = "mdi-multimedia" }
        });
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        var layout = GetLayout(ParseYamlFile(_settingsPath));
        var custom = GetEntry(layout, "Custom");
        Assert.Multiple(() =>
        {
            Assert.That(custom["icon"], Is.EqualTo("user-custom"));
            Assert.That(custom["style"], Is.EqualTo("column"));
            Assert.That(GetEntry(layout, "Media")["icon"], Is.EqualTo("mdi-multimedia"));
        });
    }

    [Test]
    public async Task WriteServices_NoOp_WhenNoCategoryHasDefaultIcon()
    {
        var manager = CreateManager(); // no Categories at all
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        Assert.That(File.Exists(_settingsPath), Is.False,
            "settings.yaml should not be created when no category has a default icon.");
    }

    [Test]
    public async Task WriteServices_TranslatesHomarrLabsCategoryIconToHomepageNoPrefix()
    {
        // Homepage declares HomarrLabs as native with prefix "" — `hl-jellyfin` should land
        // as `icon: jellyfin` in settings.yaml without any CDN probe.
        var sources = new[] { new StubIconSource(DashboardIconSourceType.HomarrLabs, "hl-") };
        var manager = CreateManager(
            categories: new() { ["Media"] = new CategoryConfig { Icon = "hl-jellyfin" } },
            iconSources: sources);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        Assert.That(GetEntry(GetLayout(ParseYamlFile(_settingsPath)), "Media")["icon"],
            Is.EqualTo("jellyfin"));
    }

    [Test]
    public async Task WriteServices_PassesMdiCategoryIconThroughForHomepage()
    {
        var sources = new[] { new StubIconSource(DashboardIconSourceType.MaterialDesignIcons, "mdi-") };
        var manager = CreateManager(
            categories: new() { ["Media"] = new CategoryConfig { Icon = "mdi-multimedia" } },
            iconSources: sources);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);

        Assert.That(GetEntry(GetLayout(ParseYamlFile(_settingsPath)), "Media")["icon"],
            Is.EqualTo("mdi-multimedia"));
    }

    [Test]
    public async Task WriteServices_SkipsCategoriesWithNullIcon()
    {
        var manager = CreateManager(new()
        {
            ["Media"]  = new CategoryConfig { Icon = "mdi-multimedia" },
            ["Custom"] = new CategoryConfig { Icon = null },
        });
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media",  null, null, "media-01", false, autogenerated: true),
            new("Thing",    "https://thing.example",    "Custom", null, null, "host-1",   false, autogenerated: true),
        };

        await manager.WriteServices(services);

        var layout = GetLayout(ParseYamlFile(_settingsPath));
        Assert.Multiple(() =>
        {
            Assert.That(GetEntry(layout, "Media")["icon"], Is.EqualTo("mdi-multimedia"));
            Assert.That(layout, Does.Not.ContainKey("Custom"),
                "Null-icon categories must not get a layout entry.");
        });
    }
}
