using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Dsm.Shared.Tests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class HomepageDashboardManagerTests : BaseTest
{
    private HomepageDashboardManager _homepageDashboardManager = null!;
    private string _homepageServicesDir = null!;
    private string _homepageServicesPath = null!;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
        // DI is built per-test in SetUp so the DashboardManagerConfig picks up the per-test path.
    }

    [SetUp]
    public void Setup()
    {
        _homepageServicesDir = Path.Combine(Path.GetTempPath(), $"dsm_homepage_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_homepageServicesDir);
        _homepageServicesPath = Path.Combine(_homepageServicesDir, HomepageDashboardManager.ServicesFileName);
        File.Copy(TestDataUtilities.GetTestDataPath("homepage_services.yml"), _homepageServicesPath, overwrite: true);

        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        _homepageDashboardManager = (HomepageDashboardManager)factory.Create(config);
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_homepageServicesDir))
        {
            Directory.Delete(_homepageServicesDir, recursive: true);
        }
    }

    [Test]
    public async Task ListServicesReturnsFixtureContents()
    {
        var services = await _homepageDashboardManager.ListServices();

        Assert.That(services, Has.Count.EqualTo(2));

        var jellyfin = services.Single(s => s.Name == "Jellyfin");
        Assert.Multiple(() =>
        {
            Assert.That(jellyfin.Url, Is.EqualTo("https://jellyfin.example.com"));
            Assert.That(jellyfin.Category, Is.EqualTo("Media"));
            Assert.That(jellyfin.Icon, Is.EqualTo("jellyfin.png"));
            Assert.That(jellyfin.ImageUrl, Is.Null);
            Assert.That(jellyfin.Hostname, Is.EqualTo("media-01-docker"));
            Assert.That(jellyfin.Autogenerated, Is.True);
        });

        var blog = services.Single(s => s.Name == "Personal Blog");
        Assert.That(blog.Autogenerated, Is.False, "Entries without _autogenerated should round-trip as not autogenerated");
    }

    [Test]
    public async Task WriteServicesRoundTripsThroughListServices()
    {
        var newService = new Service(
            "Flood", "https://flood.example.com", "Downloading",
            null, null, "nas-01-docker", false, autogenerated: true);

        await _homepageDashboardManager.WriteServices(new List<Service> { newService });

        var roundTripped = await _homepageDashboardManager.ListServices();
        var flood = roundTripped.Single(s => s.Name == "Flood");
        Assert.Multiple(() =>
        {
            Assert.That(flood.Url, Is.EqualTo("https://flood.example.com"));
            Assert.That(flood.Category, Is.EqualTo("Downloading"));
            Assert.That(flood.Hostname, Is.EqualTo("nas-01-docker"));
            Assert.That(flood.Autogenerated, Is.True);
        });
    }

    [Test]
    public async Task ServiceDefaultsName_RoundTripsThroughYaml()
    {
        var service = new Service(
            "AdGuard Home (network-01)", "https://ag.example", "Network",
            null, null, "network-01", false, autogenerated: true,
            serviceDefaultsName: "Adguardhome");

        await _homepageDashboardManager.WriteServices(new List<Service> { service });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("_serviceDefaultsName: Adguardhome"));

        var roundTripped = await _homepageDashboardManager.ListServices();
        var loaded = roundTripped.Single(s => s.Name == "AdGuard Home (network-01)");
        Assert.That(loaded.ServiceDefaultsName, Is.EqualTo("Adguardhome"));
    }

    [Test]
    public async Task ServiceDefaultsName_OmittedFromYaml_WhenNull()
    {
        var service = new Service(
            "Plain Service", "https://plain.example", "Other",
            null, null, "host", false, autogenerated: true);

        await _homepageDashboardManager.WriteServices(new List<Service> { service });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("_serviceDefaultsName"));
    }

    [Test]
    public async Task ListServices_ReturnsEmpty_WhenConfigFileMissing()
    {
        File.Delete(_homepageServicesPath);

        var services = await _homepageDashboardManager.ListServices();

        Assert.That(services, Is.Empty);
    }

    [Test]
    public async Task WriteServicesWritesExactlyWhatItIsGiven()
    {
        await _homepageDashboardManager.WriteServices(new List<Service>());

        var services = await _homepageDashboardManager.ListServices();

        Assert.That(services, Is.Empty,
            "Manager writes what it is given — preservation is the combiner/processor's job.");
    }

    [Test]
    public async Task WriteServicesPreservesAutogeneratedFlagPerService()
    {
        var userEntry = new Service(
            "Personal Blog", "https://blog.example.com", "Links",
            "mdi-rss", null, null, false, autogenerated: false);
        var autoEntry = new Service(
            "Jellyfin", "https://jellyfin.example.com", "Media",
            "jellyfin.png", null, "media-01-docker", false, autogenerated: true);

        await _homepageDashboardManager.WriteServices(new List<Service> { userEntry, autoEntry });

        var services = await _homepageDashboardManager.ListServices();
        Assert.Multiple(() =>
        {
            Assert.That(services.Single(s => s.Name == "Personal Blog").Autogenerated, Is.False);
            Assert.That(services.Single(s => s.Name == "Jellyfin").Autogenerated, Is.True);
        });
    }

    [Test]
    public async Task WriteServicesMapsImageUrlVsIconCorrectly()
    {
        var withUrlIcon = new Service(
            "Grafana", "https://grafana.example.com", "Monitoring",
            null, "https://cdn.example.com/grafana.svg", "mon-01", false, autogenerated: true);
        var withNamedIcon = new Service(
            "Pihole", "https://pihole.example.com", "Network",
            "mdi-pi-hole", null, "net-01", false, autogenerated: true);

        await _homepageDashboardManager.WriteServices(new List<Service> { withUrlIcon, withNamedIcon });

        var services = await _homepageDashboardManager.ListServices();
        var grafana = services.Single(s => s.Name == "Grafana");
        var pihole = services.Single(s => s.Name == "Pihole");
        Assert.Multiple(() =>
        {
            Assert.That(grafana.ImageUrl, Is.EqualTo("https://cdn.example.com/grafana.svg"));
            Assert.That(grafana.Icon, Is.Null);
            Assert.That(pihole.Icon, Is.EqualTo("mdi-pi-hole"));
            Assert.That(pihole.ImageUrl, Is.Null);
        });
    }

    private HomepageDashboardManager CreateManagerWithStatusMonitoring(bool enabled)
    {
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        return (HomepageDashboardManager)factory.Create(new DashboardManagerConfig
        {
            DashboardManagerType = DashboardManagerType.Homepage,
            DashboardConfigDirectoryPath = _homepageServicesDir,
            EnableStatusMonitoring = enabled
        });
    }

    [Test]
    public async Task EnableStatusMonitoring_True_EmitsSiteMonitorWithHref()
    {
        var manager = CreateManagerWithStatusMonitoring(true);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
            new("Grafana",  "https://grafana.example",  "Monitoring", null, null, "mon-01",   false, autogenerated: true),
        };

        await manager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_homepageServicesPath);

        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("siteMonitor: https://jellyfin.example"));
            Assert.That(written, Does.Contain("siteMonitor: https://grafana.example"));
        });
    }

    [Test]
    public async Task EnableStatusMonitoring_False_OmitsSiteMonitor()
    {
        var manager = CreateManagerWithStatusMonitoring(false);
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        };

        await manager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_homepageServicesPath);

        Assert.That(written, Does.Not.Contain("siteMonitor"));
    }

    [Test]
    public async Task WriteServices_TitleCasesLowercaseCategories()
    {
        var services = new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "media", null, null, "media-01", false, autogenerated: true),
        };

        await _homepageDashboardManager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_homepageServicesPath);

        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("- Media:"));
            Assert.That(written, Does.Not.Contain("- media:"));
        });
    }

    [TestCase("3d printing")]
    [TestCase("3D printing")]
    public async Task WriteServices_UppercasesLetterAfterDigitInCategory(string input)
    {
        var services = new List<Service>
        {
            new("Spoolman", "https://spoolman.example", input, null, null, "print-01", false, autogenerated: true),
        };

        await _homepageDashboardManager.WriteServices(services);
        var written = await File.ReadAllTextAsync(_homepageServicesPath);

        Assert.That(written, Does.Contain("- 3D Printing:"));
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Homepage,
                    DashboardConfigDirectoryPath = _homepageServicesDir,
                },
            };
        });
    }
}
