using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class HomepageDashboardManagerWidgetServerScopingTests : BaseTest
{
    private TestTempDir _tempDir = null!;
    private string _homepageServicesPath = null!;
    private string? _widgetsPath;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
    }

    [SetUp]
    public void Setup()
    {
        _tempDir = TestTempDir.Create("dsm_homepage_widget_scope");
        _homepageServicesPath = _tempDir.RootedPath(HomepageDashboardManager.ServicesFileName);
        _widgetsPath = null;
    }

    [TearDown]
    public void TearDown() => _tempDir.Dispose();

    private HomepageDashboardManager CreateManager()
    {
        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        return (HomepageDashboardManager)factory.Create(config);
    }

    private void WriteWidgetsFile(string yaml)
    {
        _widgetsPath = _tempDir.RootedPath("widgets.yaml");
        File.WriteAllText(_widgetsPath, yaml);
    }

    [Test]
    public async Task MultipleEntriesSameName_DifferentServer_EachMatchesCorrectService()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://adguardhome.example
            - adguardhome:
                server: pi-rack
                widget:
                  type: adguard
                  url: https://adguardhome-02.example
            - adguardhome:
                server: network-03
                widget:
                  type: adguard
                  url: https://adguardhome-03.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag01.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (pi-rack)", "https://ag02.example", "Network", null, null, "pi-rack", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (network-03)", "https://ag03.example", "Network", null, null, "network-03", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://adguardhome.example"));
            Assert.That(written, Does.Contain("url: https://adguardhome-02.example"));
            Assert.That(written, Does.Contain("url: https://adguardhome-03.example"));
        });
    }

    [Test]
    public async Task ServerMatch_BeatsUnscopedEntry()
    {
        WriteWidgetsFile("""
            - adguardhome:
                widget:
                  type: adguard
                  url: https://unscoped.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://scoped.example"));
            Assert.That(written, Does.Not.Contain("url: https://unscoped.example"));
        });
    }

    [Test]
    public async Task UnscopedFallback_Used_WhenHostnameDoesNotMatchAnyServerScopedEntry()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: other-host
                widget:
                  type: adguard
                  url: https://other.example
            - adguardhome:
                widget:
                  type: adguard
                  url: https://fallback.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://fallback.example"));
            Assert.That(written, Does.Not.Contain("url: https://other.example"));
        });
    }

    [Test]
    public async Task NoMatch_WhenAllEntriesAreServerScopedAndNoneMatch()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: other-host
                widget:
                  type: adguard
                  url: https://other.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget:"));
    }

    [Test]
    public async Task ServerMatch_IsCaseInsensitive()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: Network-01
                widget:
                  type: adguard
                  url: https://scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("url: https://scoped.example"));
    }

    [Test]
    public async Task ServerMatchOnServiceDefaultsName_BeatsUnscopedNameMatch()
    {
        WriteWidgetsFile("""
            - AdGuard Home (network-01):
                widget:
                  type: adguard
                  url: https://name-unscoped.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://defaults-scoped.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://defaults-scoped.example"));
            Assert.That(written, Does.Not.Contain("url: https://name-unscoped.example"));
        });
    }

    [Test]
    public async Task DuplicateEntry_SameNameAndServer_LastWins()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://first.example
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://second.example
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("url: https://second.example"));
            Assert.That(written, Does.Not.Contain("url: https://first.example"));
        });
    }

    [Test]
    public async Task WidgetMatch_SurvivesRoundTrip_AcrossMultipleHosts()
    {
        WriteWidgetsFile("""
            - adguardhome:
                server: network-01
                widget:
                  type: adguard
                  url: https://ag-01.example
            - adguardhome:
                server: pi-rack
                widget:
                  type: adguard
                  url: https://ag-02.example
            - adguardhome:
                server: network-03
                widget:
                  type: adguard
                  url: https://ag-03.example
            """);
        var manager = CreateManager();

        var initial = new List<Service>
        {
            new("AdGuard Home (network-01)", "https://ag01.example", "Network", null, null, "network-01", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (pi-rack)", "https://ag02.example", "Network", null, null, "pi-rack", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
            new("AdGuard Home (network-03)", "https://ag03.example", "Network", null, null, "network-03", false, autogenerated: true, serviceDefaultsName: "Adguardhome"),
        };
        await manager.WriteServices(initial);

        var firstWrite = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(firstWrite, Does.Contain("url: https://ag-01.example"));
            Assert.That(firstWrite, Does.Contain("url: https://ag-02.example"));
            Assert.That(firstWrite, Does.Contain("url: https://ag-03.example"));
        });

        var listed = await manager.ListServices();
        Assert.That(listed, Has.Count.EqualTo(3));
        Assert.That(listed.All(s => s.ServiceDefaultsName == "Adguardhome"), Is.True);

        await manager.WriteServices(listed);

        var secondWrite = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(secondWrite, Does.Contain("url: https://ag-01.example"));
            Assert.That(secondWrite, Does.Contain("url: https://ag-02.example"));
            Assert.That(secondWrite, Does.Contain("url: https://ag-03.example"));
        });
    }

    [Test]
    public async Task SiteMonitor_IsOmitted_ForServiceWithWidget_WhenStatusMonitoringEnabled()
    {
        WriteWidgetsFile("""
            - Sonarr:
                widget:
                  type: sonarr
                  url: http://sonarr.host
                  key: k
            """);

        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var manager = (HomepageDashboardManager)factory.Create(new DashboardManagerConfig
        {
            DashboardManagerType = DashboardManagerType.Homepage,
            DashboardConfigDirectoryPath = _tempDir.Path,
            SourceHomepageServiceWidgetsFilePath = _widgetsPath,
            EnableStatusMonitoring = true,
        });

        await manager.WriteServices(new List<Service>
        {
            new("Sonarr",   "https://sonarr.example",   "Media", null, null, "media-01", false, autogenerated: true),
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("siteMonitor: https://jellyfin.example"));
            Assert.That(written, Does.Not.Contain("siteMonitor: https://sonarr.example"));
        });
    }

    [Test]
    public async Task BothWidgetAndWidgets_PrefersWidgets()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: single
                  url: http://single
                widgets:
                  - type: listed
                    url: http://listed
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: listed"));
            Assert.That(written, Does.Not.Contain("type: single"));
        });
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Homepage,
                    DashboardConfigDirectoryPath = _tempDir.Path,
                    SourceHomepageServiceWidgetsFilePath = _widgetsPath,
                },
            };
        });
    }
}
