using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Shared.Models;
using Dsm.Shared.Tests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Tests.UnitTests;

public class HomepageDashboardManagerWidgetsTests : BaseTest
{
    private string _homepageServicesDir = null!;
    private string _homepageServicesPath = null!;
    private string? _widgetsPath;

    [OneTimeSetUp]
    public override void OneTimeSetUp()
    {
    }

    [SetUp]
    public void Setup()
    {
        _homepageServicesDir = Path.Combine(Path.GetTempPath(), $"dsm_homepage_widgets_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_homepageServicesDir);
        _homepageServicesPath = Path.Combine(_homepageServicesDir, HomepageDashboardManager.ServicesFileName);
        _widgetsPath = null;
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_homepageServicesDir))
        {
            Directory.Delete(_homepageServicesDir, recursive: true);
        }
    }

    private HomepageDashboardManager CreateManager()
    {
        ServiceProvider = ServiceProviderFactory.Create(ConfigureConfiguration, AddServices);
        var factory = ServiceProvider.GetRequiredService<DashboardManagerFactory>();
        var config = ServiceProvider.GetRequiredService<IOptions<ManagerOptions>>()
            .Value.DashboardManagers.Single();
        return (HomepageDashboardManager)factory.Create(config);
    }

    private void WriteWidgetsFile(string yaml)
    {
        _widgetsPath = Path.Combine(_homepageServicesDir, "widgets.yaml");
        File.WriteAllText(_widgetsPath, yaml);
    }

    [Test]
    public async Task SingleWidget_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host.or.ip
                  key: apikey
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widget:"));
            Assert.That(written, Does.Contain("type: emby"));
            Assert.That(written, Does.Contain("key: apikey"));
            Assert.That(written, Does.Not.Contain("widgets:"));
        });
    }

    [Test]
    public async Task WidgetsList_IsMergedIntoMatchingService()
    {
        WriteWidgetsFile("""
            - Sonarr:
                widgets:
                  - type: sonarr
                    url: http://sonarr.host
                    key: aaa
                  - type: uptimekuma
                    url: http://uptime.host
                    slug: status
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Sonarr", "https://sonarr.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: sonarr"));
            Assert.That(written, Does.Contain("type: uptimekuma"));
            Assert.That(written, Does.Contain("slug: status"));
        });
    }

    [Test]
    public async Task WidgetMatch_IsCaseInsensitive()
    {
        WriteWidgetsFile("""
            - emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Contain("type: emby"));
    }

    [Test]
    public async Task ServiceWithoutMatchingWidget_GetsNoWidgetBlock()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: emby
                  url: http://emby.host
                  key: k
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Jellyfin", "https://jellyfin.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task MissingWidgetsFile_DoesNotThrow_AndProducesNoWidgets()
    {
        _widgetsPath = Path.Combine(_homepageServicesDir, "does-not-exist.yaml");
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task NullWidgetsPath_DoesNotLoad()
    {
        _widgetsPath = null;
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.That(written, Does.Not.Contain("widget"));
    }

    [Test]
    public async Task BothWidgetAndWidgets_PrefersWidgets()
    {
        WriteWidgetsFile("""
            - Emby:
                widget:
                  type: single
                  url: http://single
                widgets:
                  - type: listed
                    url: http://listed
            """);
        var manager = CreateManager();

        await manager.WriteServices(new List<Service>
        {
            new("Emby", "https://emby.example", "Media", null, null, "media-01", false, autogenerated: true),
        });

        var written = await File.ReadAllTextAsync(_homepageServicesPath);
        Assert.Multiple(() =>
        {
            Assert.That(written, Does.Contain("widgets:"));
            Assert.That(written, Does.Contain("type: listed"));
            Assert.That(written, Does.Not.Contain("type: single"));
        });
    }

    protected override void AddServices(IConfiguration configuration, IServiceCollection services)
    {
        base.AddServices(configuration, services);

        services.Configure<ManagerOptions>(opts =>
        {
            opts.DashboardManagers = new List<DashboardManagerConfig>
            {
                new DashboardManagerConfig
                {
                    DashboardManagerType = DashboardManagerType.Homepage,
                    DashboardConfigDirectoryPath = _homepageServicesDir,
                    SourceHomepageServiceWidgetsFilePath = _widgetsPath,
                },
            };
        });
    }
}
