using Dsm.Managers.Services;
using Dsm.Shared.Models;
using Microsoft.Extensions.DependencyInjection;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class ServiceFactoryTests : ManagerTestFixtureHostedTestBase
{
    private ServiceWithDefaultsFactory _serviceWithDefaultsFactory;

    public override void OneTimeSetUp()
    {
        base.OneTimeSetUp();
        _serviceWithDefaultsFactory = ServiceProvider.GetRequiredService<ServiceWithDefaultsFactory>();
    }

    [Test]
    public void ServiceDefaultsName_OverridesDefaultsLookup()
    {
        var service = new Service("PiKVM HID", "https://example.com", null, null, null, null, false, serviceDefaultsName: "Proxmox");

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.Category, Is.EqualTo("infrastructure"));
    }

    [Test]
    public void NameWithHostnameFormatString_IsApplied()
    {
        var service = new Service("Traefik", "https://example.com", null, null, null, "host1", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.Name, Is.EqualTo("Traefik (host1)"));
    }

    [Test]
    public void RelativeImagePath_IsResolvedAgainstServiceUrl()
    {
        var service = new Service("Grafana", "https://grafana.example.com", null, null, "/public/img/grafana_icon.svg", "host1", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.ImageUrl, Is.EqualTo("https://grafana.example.com/public/img/grafana_icon.svg"));
    }

    [Test]
    public void AbsoluteImagePath_PassesThroughUnchanged()
    {
        var service = new Service("Healthchecks", "https://healthchecks.example.com", null, null, "https://healthchecks.io/static/img/favicon.png", "host1", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.ImageUrl, Is.EqualTo("https://healthchecks.io/static/img/favicon.png"));
    }

    [Test]
    public void DefaultsLookup_IsCaseInsensitive()
    {
        var service = new Service("TRAEFIK", "https://example.com", null, null, null, "host1", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.Name, Is.EqualTo("Traefik (host1)"));
        Assert.That(result.Category, Is.EqualTo("network"));
    }

    [Test]
    public void NameWithHostnameFormat_AllowsBraceChar()
    {
        var service = new Service("Traefik", "https://example.com", null, null, null, "a{b}c", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.Name, Is.EqualTo("Traefik (a{b}c)"));
    }

    [Test]
    public void ServiceDefaultsName_IsStampedFromDefaultsLookupKey()
    {
        var service = new Service("Adguardhome", "https://example.com", null, null, null, "network-01", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.Multiple(() =>
        {
            Assert.That(result.Name, Is.EqualTo("AdGuard Home (network-01)"));
            Assert.That(result.ServiceDefaultsName, Is.EqualTo("Adguardhome"));
        });
    }

    [Test]
    public void ServiceDefaultsName_IsNullWhenNoDefaultsMatch()
    {
        var service = new Service("NoSuchService", "https://example.com", null, null, null, "host1", false);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.ServiceDefaultsName, Is.Null);
    }

    [Test]
    public void ServiceDefaultsName_ExplicitValueIsPreserved()
    {
        var service = new Service("My Custom Name", "https://example.com", null, null, null, "host1", false, serviceDefaultsName: "Proxmox");

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.ServiceDefaultsName, Is.EqualTo("Proxmox"));
    }

    [Test]
    public void AutogeneratedFlag_IsPreserved()
    {
        var service = new Service("SomeService", "https://example.com", "media", null, null, "h", false, autogenerated: true);

        var result = _serviceWithDefaultsFactory.CreateWithDefaults(service);

        Assert.That(result.Autogenerated, Is.True);
    }
}
