using Dsm.Managers.Services;
using Dsm.Shared.Models;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class ServicesCombinerTests
{
    private readonly ServicesCombiner _servicesCombiner = new ServicesCombiner();

    [Test]
    public void AutogeneratedExisting_SameName_DifferentHostname_BothSurvive()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.old", "media", null, null, "old-host", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "media", null, null, "new-host", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result.Select(s => s.Url),
            Is.EquivalentTo(new[] { "https://jellyfin.old", "https://jellyfin.new" }));
    }

    [Test]
    public void AutogeneratedExisting_SameName_SameHostname_IsReplaced()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.old", "media", null, null, "host-1", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "media", null, null, "host-1", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Url, Is.EqualTo("https://jellyfin.new"));
    }

    [Test]
    public void AutogeneratedExisting_NullHostname_FallsBackToNameMatch()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.old", "media", null, null, null, false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "media", null, null, null, false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Url, Is.EqualTo("https://jellyfin.new"));
    }

    [Test]
    public void AutogeneratedExisting_WithMatchingHostname_IsDropped()
    {
        var existing = new List<Service>
        {
            new Service("Old", "https://old.example", "media", null, null, "host-1", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("New", "https://new.example", "media", null, null, "host-1", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "New" }));
    }

    [Test]
    public void AutogeneratedExisting_WithNoOverlap_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("Existing", "https://existing.example", "media", null, null, "host-a", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("New", "https://new.example", "media", null, null, "host-b", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "Existing", "New" }));
    }

    [Test]
    public void UserAddedExisting_WithMatchingTitle_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.user", "media", null, null, "user-host", false, autogenerated: false),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.auto", "media", null, null, "auto-host", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result.Select(s => s.Url),
            Is.EquivalentTo(new[] { "https://jellyfin.user", "https://jellyfin.auto" }));
    }

    [Test]
    public void UserAddedExisting_WithMatchingHostname_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("CustomTool", "https://custom.example", "utilities", null, null, "host-1", false, autogenerated: false),
        };
        var incoming = new List<Service>
        {
            new Service("Other", "https://other.example", "utilities", null, null, "host-1", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "CustomTool", "Other" }));
    }

    [Test]
    public void Result_IsSortedByCategoryThenName()
    {
        var incoming = new List<Service>
        {
            new Service("Zeta", "https://z.example", "media", null, null, "h", false, autogenerated: true),
            new Service("Alpha", "https://a.example", "network", null, null, "h", false, autogenerated: true),
            new Service("Beta", "https://b.example", "media", null, null, "h", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(new List<Service>(), incoming);

        Assert.That(result.Select(s => (s.Category, s.Name)), Is.EqualTo(new[]
        {
            ("media", "Beta"),
            ("media", "Zeta"),
            ("network", "Alpha"),
        }));
    }

    [Test]
    public void EmptyNewServices_ReturnsAllExisting()
    {
        var existing = new List<Service>
        {
            new Service("A", "https://a.example", "c", null, null, "h", false, autogenerated: true),
            new Service("B", "https://b.example", "c", null, null, "h", false, autogenerated: false),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, new List<Service>());

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "A", "B" }));
    }

    [Test]
    public void SameHostname_DifferentProviderId_BothSurvive()
    {
        var existing = new List<Service>
        {
            new Service("Scrutiny", "https://scrutiny.old", "infra", null, null, "nas-01", false, autogenerated: true, providerId: "nas-01-docker"),
        };
        var incoming = new List<Service>
        {
            new Service("Nextcloud", "https://nextcloud.new", "cloud", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "Scrutiny", "Nextcloud" }));
    }

    [Test]
    public void SameHostname_SameProviderId_IncomingReplaces()
    {
        var existing = new List<Service>
        {
            new Service("Scrutiny", "https://scrutiny.old", "infra", null, null, "nas-01", false, autogenerated: true, providerId: "nas-01-docker"),
        };
        var incoming = new List<Service>
        {
            new Service("Scrutiny", "https://scrutiny.new", "infra", null, null, "nas-01", false, autogenerated: true, providerId: "nas-01-docker"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Url, Is.EqualTo("https://scrutiny.new"));
    }

    [Test]
    public void MixedProviderIds_EachReplacesItsOwn()
    {
        var existing = new List<Service>
        {
            new Service("OldTraefik", "https://old-t.example", "c", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik"),
            new Service("OldDocker", "https://old-d.example", "c", null, null, "nas-01", false, autogenerated: true, providerId: "nas-01-docker"),
        };
        var incoming = new List<Service>
        {
            new Service("NewTraefik", "https://new-t.example", "c", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "NewTraefik", "OldDocker" }));
    }

    [Test]
    public void SameNameAndHostname_DifferentProviderId_DedupKeepsIncoming()
    {
        var existing = new List<Service>
        {
            new Service("Scrutiny", "https://scrutiny.docker", "infra", null, null, "nas-01", false, autogenerated: true, providerId: "nas-01-docker"),
        };
        var incoming = new List<Service>
        {
            new Service("Scrutiny", "https://scrutiny.traefik", "infra", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Url, Is.EqualTo("https://scrutiny.traefik"));
        Assert.That(result[0].ProviderId, Is.EqualTo("docker-01-traefik"));
    }

    [Test]
    public void FailedSource_ProviderIdAbsentFromPost_ExistingPersists()
    {
        var existing = new List<Service>
        {
            new Service("FromTraefik0", "https://t0.example", "c", null, null, "docker-01", false, autogenerated: true, providerId: "docker-01-traefik-0"),
            new Service("FromTraefik2", "https://t2.example", "c", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik-2"),
        };
        var incoming = new List<Service>
        {
            new Service("FromTraefik0New", "https://t0-new.example", "c", null, null, "docker-01", false, autogenerated: true, providerId: "docker-01-traefik-0"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "FromTraefik0New", "FromTraefik2" }));
    }

    [Test]
    public void NullIncomingProviderId_ExistingWithProviderId_IsPreserved()
    {
        var existing = new List<Service>
        {
            new Service("Tagged", "https://tagged.example", "c", null, null, "nas-01", false, autogenerated: true, providerId: "docker-01-traefik"),
        };
        var incoming = new List<Service>
        {
            new Service("Legacy", "https://legacy.example", "c", null, null, "nas-01", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "Tagged", "Legacy" }));
    }

    [Test]
    public void NullIncomingProviderId_NullExistingProviderId_HostnameFallback()
    {
        var existing = new List<Service>
        {
            new Service("Old", "https://old.example", "c", null, null, "nas-01", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("New", "https://new.example", "c", null, null, "nas-01", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "New" }));
    }

    [Test]
    public void StaleNullProviderId_SameUrlAndHostname_DedupedByUrl()
    {
        var existing = new List<Service>
        {
            new Service("Tsdproxy", "https://tsdproxy.docker-01.example", "uncategorized", null, null, "docker-01", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("TSDProxy (docker-01)", "https://tsdproxy.docker-01.example", "network", null, null, "docker-01", false, autogenerated: true, providerId: "docker-01-traefik"),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Name, Is.EqualTo("TSDProxy (docker-01)"));
        Assert.That(result[0].ProviderId, Is.EqualTo("docker-01-traefik"));
    }
}
