using Dsm.Managers.Services;
using Dsm.Shared.Models;

namespace Dsm.Managers.Tests.UnitTests;

[CancelAfter(TestTimeouts.HungThresholdMs)]
public class ServicesCombinerTests
{
    private readonly ServicesCombiner _servicesCombiner = new ServicesCombiner();

    [Test]
    public void AutogeneratedExisting_WithMatchingTitle_IsDropped()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.old", "media", null, null, "old-host", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.new", "media", null, null, "new-host", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(1));
        Assert.That(result[0].Url, Is.EqualTo("https://jellyfin.new"));
    }

    [Test]
    public void AutogeneratedExisting_WithMatchingHostname_IsDropped()
    {
        var existing = new List<Service>
        {
            new Service("Old", "https://old.example", "media", null, null, "host-1", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("New", "https://new.example", "media", null, null, "host-1", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "New" }));
    }

    [Test]
    public void AutogeneratedExisting_WithNoOverlap_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("Existing", "https://existing.example", "media", null, null, "host-a", false, autogenerated: true),
        };
        var incoming = new List<Service>
        {
            new Service("New", "https://new.example", "media", null, null, "host-b", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "Existing", "New" }));
    }

    [Test]
    public void UserAddedExisting_WithMatchingTitle_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.user", "media", null, null, "user-host", false, autogenerated: false),
        };
        var incoming = new List<Service>
        {
            new Service("Jellyfin", "https://jellyfin.auto", "media", null, null, "auto-host", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result, Has.Count.EqualTo(2));
        Assert.That(result.Select(s => s.Url),
            Is.EquivalentTo(new[] { "https://jellyfin.user", "https://jellyfin.auto" }));
    }

    [Test]
    public void UserAddedExisting_WithMatchingHostname_IsKept()
    {
        var existing = new List<Service>
        {
            new Service("CustomTool", "https://custom.example", "utilities", null, null, "host-1", false, autogenerated: false),
        };
        var incoming = new List<Service>
        {
            new Service("Other", "https://other.example", "utilities", null, null, "host-1", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, incoming);

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "CustomTool", "Other" }));
    }

    [Test]
    public void Result_IsSortedByCategoryThenName()
    {
        var incoming = new List<Service>
        {
            new Service("Zeta", "https://z.example", "media", null, null, "h", false, autogenerated: true),
            new Service("Alpha", "https://a.example", "network", null, null, "h", false, autogenerated: true),
            new Service("Beta", "https://b.example", "media", null, null, "h", false, autogenerated: true),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(new List<Service>(), incoming);

        Assert.That(result.Select(s => (s.Category, s.Name)), Is.EqualTo(new[]
        {
            ("media", "Beta"),
            ("media", "Zeta"),
            ("network", "Alpha"),
        }));
    }

    [Test]
    public void EmptyNewServices_ReturnsAllExisting()
    {
        var existing = new List<Service>
        {
            new Service("A", "https://a.example", "c", null, null, "h", false, autogenerated: true),
            new Service("B", "https://b.example", "c", null, null, "h", false, autogenerated: false),
        };

        var result = _servicesCombiner.CombineExistingServicesWithNewServices(existing, new List<Service>());

        Assert.That(result.Select(s => s.Name), Is.EquivalentTo(new[] { "A", "B" }));
    }
}
