using Dsm.Managers.Configuration;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Services;

public class ServiceWithDefaultsFactory
{
    private readonly ServiceDefaultOptions _serviceDefaultOptions;

    public ServiceWithDefaultsFactory(IOptions<ServiceDefaultOptions> defaultOptions)
    {
        _serviceDefaultOptions = defaultOptions.Value;
    }

    public Service CreateWithDefaults(Service service)
    {
        var lookupName = !string.IsNullOrEmpty(service.ServiceDefaultsName)
            ? service.ServiceDefaultsName
            : service.Name;

        _serviceDefaultOptions.Services.TryGetValue(lookupName, out var defaultServiceConfig);

        var name = ApplyNameFormat(service, defaultServiceConfig);
        var category = !string.IsNullOrEmpty(service.Category) ? service.Category : defaultServiceConfig?.Category;
        var icon = !string.IsNullOrEmpty(service.Icon) ? service.Icon : defaultServiceConfig?.Icon;
        var imagePath = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : defaultServiceConfig?.ImagePath;
        var imageUrl = ResolveImageUrl(imagePath, service.Url);

        return new Service(
            name,
            service.Url,
            category,
            icon,
            imageUrl,
            service.Hostname,
            service.Ignore,
            service.Autogenerated,
            service.ServiceDefaultsName ?? (defaultServiceConfig is not null ? lookupName : null));
    }

    private static string ApplyNameFormat(Service service, ServiceConfig? defaultServiceConfig)
    {
        var format = defaultServiceConfig?.NameWithHostnameFormatString;
        if (string.IsNullOrEmpty(format) || string.IsNullOrEmpty(service.Hostname))
        {
            return service.Name;
        }
        return format.Replace("%s", service.Hostname);
    }

    private static string? ResolveImageUrl(string? imagePath, string? serviceUrl)
    {
        if (string.IsNullOrEmpty(imagePath))
        {
            return null;
        }
        if (Uri.TryCreate(imagePath, UriKind.Absolute, out var absolute) &&
            (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps))
        {
            return absolute.ToString();
        }
        if (!string.IsNullOrEmpty(serviceUrl) &&
            Uri.TryCreate(serviceUrl, UriKind.Absolute, out var baseUri))
        {
            return new Uri(baseUri, imagePath).ToString();
        }
        return imagePath;
    }
}
