using Dsm.Shared.Models;

namespace Dsm.Managers.Services;

public class ServicesCombiner
{
    public List<Service> CombineExistingServicesWithNewServices(
        List<Service> existingServices,
        List<Service> newServices)
    {
        var incomingProviderIds = newServices
            .Select(s => s.ProviderId)
            .Where(id => id is not null)
            .ToHashSet();

        List<Service> survivors;

        if (incomingProviderIds.Count > 0)
        {
            survivors = existingServices
                .Where(e => !e.Autogenerated || !incomingProviderIds.Contains(e.ProviderId))
                .ToList();
        }
        else
        {
            var newTitles = newServices
                .Select(s => s.Name)
                .ToHashSet();
            var newHostnames = newServices
                .Select(s => s.Hostname)
                .Where(h => !string.IsNullOrEmpty(h))
                .ToHashSet();

            survivors = existingServices
                .Where(e =>
                {
                    if (!e.Autogenerated) return true;
                    if (e.ProviderId is not null) return true;
                    var overlaps = !string.IsNullOrEmpty(e.Hostname)
                        ? newHostnames.Contains(e.Hostname)
                        : newTitles.Contains(e.Name);
                    return !overlaps;
                })
                .ToList();
        }

        var merged = new List<Service>(newServices);
        merged.AddRange(survivors);

        var seenNames = new HashSet<(string, string?)>();
        var seenUrls = new HashSet<(string, string?)>();
        var result = new List<Service>();
        foreach (var s in merged)
        {
            if (!seenNames.Add((s.Name, s.Hostname)))
                continue;
            if (!string.IsNullOrEmpty(s.Url) && !seenUrls.Add((s.Url, s.Hostname)))
                continue;
            result.Add(s);
        }

        return result
            .OrderBy(s => s.Category)
            .ThenBy(s => s.Name)
            .ToList();
    }
}
