using System.Collections.Concurrent;
using Dsm.Managers.Configuration;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Services;

public class ServiceWithDefaultsFactory
{
    public const string HttpClientName = "homarrlabs";
    private const string BaseHomarrLabsDashboardIconUrl = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/";
    private static readonly TimeSpan NegativeCacheTtl = TimeSpan.FromHours(1);
    private static readonly ConcurrentDictionary<string, (string? Url, DateTime CachedAt)> HomarrLabsIconCache = new();

    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly IHttpClientFactory _httpClientFactory;

    public ServiceWithDefaultsFactory(
        IOptions<ServiceDefaultOptions> defaultOptions,
        IHttpClientFactory httpClientFactory)
    {
        _serviceDefaultOptions = defaultOptions.Value;
        _httpClientFactory = httpClientFactory;
    }

    public async Task<Service> CreateWithDefaultsAsync(Service service)
    {
        var lookupName = !string.IsNullOrEmpty(service.ServiceDefaultsName)
            ? service.ServiceDefaultsName
            : service.Name;

        _serviceDefaultOptions.Services.TryGetValue(lookupName, out var defaultServiceConfig);

        var name = ApplyNameFormat(service, defaultServiceConfig);
        var category = !string.IsNullOrEmpty(service.Category) ? service.Category : defaultServiceConfig?.Category;
        var icon = !string.IsNullOrEmpty(service.Icon) ? service.Icon : defaultServiceConfig?.Icon;
        var imagePath = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : defaultServiceConfig?.ImagePath;
        var imageUrl = ResolveImageUrl(imagePath, service.Url);

        if (_serviceDefaultOptions.UseHomarrLabsDashboardIcons &&
            string.IsNullOrEmpty(icon) &&
            string.IsNullOrEmpty(imageUrl))
        {
            imageUrl = await GetHomarrLabsDashboardIconUrlAsync(lookupName);
        }

        return new Service(
            name,
            service.Url,
            category,
            icon,
            imageUrl,
            service.Hostname,
            service.Ignore,
            service.Autogenerated,
            service.ServiceDefaultsName);
    }

    private static string ApplyNameFormat(Service service, ServiceConfig? defaultServiceConfig)
    {
        var format = defaultServiceConfig?.NameWithHostnameFormatString;
        if (string.IsNullOrEmpty(format) || string.IsNullOrEmpty(service.Hostname))
        {
            return service.Name;
        }
        return format.Replace("%s", service.Hostname);
    }

    private static string? ResolveImageUrl(string? imagePath, string? serviceUrl)
    {
        if (string.IsNullOrEmpty(imagePath))
        {
            return null;
        }
        if (Uri.TryCreate(imagePath, UriKind.Absolute, out var absolute) &&
            (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps))
        {
            return absolute.ToString();
        }
        if (!string.IsNullOrEmpty(serviceUrl) &&
            Uri.TryCreate(serviceUrl, UriKind.Absolute, out var baseUri))
        {
            return new Uri(baseUri, imagePath).ToString();
        }
        return imagePath;
    }

    private async Task<string?> GetHomarrLabsDashboardIconUrlAsync(string serviceName)
    {
        if (HomarrLabsIconCache.TryGetValue(serviceName, out var cached) &&
            (cached.Url is not null || DateTime.UtcNow - cached.CachedAt < NegativeCacheTtl))
        {
            return cached.Url;
        }

        var lowerCaseServiceName = serviceName.ToLowerInvariant();
        var potentialIconNames = new[]
        {
            lowerCaseServiceName.Replace(" ", string.Empty),
            lowerCaseServiceName.Replace(" ", "-"),
            lowerCaseServiceName.Replace(".", "-")
        };

        var httpClient = _httpClientFactory.CreateClient(HttpClientName);
        foreach (var potentialIconName in potentialIconNames)
        {
            var homarrLabsDashboardIconUrl = $"{BaseHomarrLabsDashboardIconUrl}{potentialIconName}.png";
            using var request = new HttpRequestMessage(HttpMethod.Head, homarrLabsDashboardIconUrl);
            using var response = await httpClient.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                HomarrLabsIconCache[serviceName] = (homarrLabsDashboardIconUrl, DateTime.UtcNow);
                return homarrLabsDashboardIconUrl;
            }
        }

        HomarrLabsIconCache[serviceName] = (null, DateTime.UtcNow);
        return null;
    }
}
