using Dsm.Managers.Configuration;
using Dsm.Managers.Services.IconSources;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers.Services;

public class ServiceWithDefaultsFactory
{
    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly Dictionary<DashboardIconSourceType, IDashboardIconSource> _iconSources;

    public ServiceWithDefaultsFactory(
        IOptions<ServiceDefaultOptions> defaultOptions,
        IEnumerable<IDashboardIconSource> iconSources)
    {
        _serviceDefaultOptions = defaultOptions.Value;
        _iconSources = iconSources.ToDictionary(s => s.Type);
    }

    public async Task<Service> CreateWithDefaultsAsync(Service service)
    {
        var lookupName = !string.IsNullOrEmpty(service.ServiceDefaultsName)
            ? service.ServiceDefaultsName
            : service.Name;

        _serviceDefaultOptions.Services.TryGetValue(lookupName, out var defaultServiceConfig);

        var name = ApplyNameFormat(service, defaultServiceConfig);
        var category = !string.IsNullOrEmpty(service.Category) ? service.Category : defaultServiceConfig?.Category;
        var icon = !string.IsNullOrEmpty(service.Icon) ? service.Icon : defaultServiceConfig?.Icon;
        var imagePath = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : defaultServiceConfig?.ImagePath;
        var imageUrl = ResolveImageUrl(imagePath, service.Url);

        if (!string.IsNullOrEmpty(icon))
        {
            var match = _iconSources.Values.FirstOrDefault(
                s => icon.StartsWith(s.Prefix, StringComparison.OrdinalIgnoreCase));
            if (match is not null)
            {
                var resolved = await match.GetIconUrl(icon[match.Prefix.Length..]);
                if (!string.IsNullOrEmpty(resolved))
                {
                    imageUrl = resolved;
                    icon = null;
                }
            }
        }

        if (string.IsNullOrEmpty(icon) && string.IsNullOrEmpty(imageUrl))
        {
            foreach (var type in _serviceDefaultOptions.FallbackIconSourceProviders)
            {
                if (!_iconSources.TryGetValue(type, out var source)) continue;
                imageUrl = await source.GetIconUrl(lookupName);
                if (!string.IsNullOrEmpty(imageUrl)) break;
            }
        }

        return new Service(
            name,
            service.Url,
            category,
            icon,
            imageUrl,
            service.Hostname,
            service.Ignore,
            service.Autogenerated,
            service.ServiceDefaultsName ?? (defaultServiceConfig is not null ? lookupName : null));
    }

    private static string ApplyNameFormat(Service service, ServiceConfig? defaultServiceConfig)
    {
        var format = defaultServiceConfig?.NameWithHostnameFormatString;
        if (string.IsNullOrEmpty(format) || string.IsNullOrEmpty(service.Hostname))
        {
            return service.Name;
        }
        return format.Replace("%s", service.Hostname);
    }

    private static string? ResolveImageUrl(string? imagePath, string? serviceUrl)
    {
        if (string.IsNullOrEmpty(imagePath))
        {
            return null;
        }
        if (Uri.TryCreate(imagePath, UriKind.Absolute, out var absolute) &&
            (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps))
        {
            return absolute.ToString();
        }
        if (!string.IsNullOrEmpty(serviceUrl) &&
            Uri.TryCreate(serviceUrl, UriKind.Absolute, out var baseUri))
        {
            return new Uri(baseUri, imagePath).ToString();
        }
        return imagePath;
    }
}
