
using Dsm.Shared.Models;

namespace Dsm.Managers.DashboardManagers.Dashy;
public class DashyItem
{
    public const string AUTOGENERATED_TAG = "_autogenerated";

    public static DashyItem Create(Service service)
    {
        var dashyIcon = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : service.Icon;
        var tags = new List<string>()
        {
            AUTOGENERATED_TAG,
            $"host={service.Hostname}"
        };

        return new DashyItem(service.Name, service.Url, dashyIcon, tags);
    }
    
    public DashyItem(string title, string url, string icon, List<string> tags)
    {
        Title = title;
        Url = url;
        Icon = icon;
        Tags = tags;
    }

    public string Title { get; set; }
    public string Url { get; set; }
    public string Icon { get; set; }
    public List<string> Tags { get; set; }
  }