
namespace Dsm.Managers.Dashy;
public class DashyItem
{
    public const string AUTOGENERATED_TAG = "_autogenerated";

    public string Title { get; set; }
    public string Url { get; set; }
    public string Icon { get; set; }
    public string Tags { get; set; }
  }