using System.ComponentModel;

namespace Dsm.Shared.Models;

public record class Service
{
    public string Name { get; init; } = string.Empty;
    public string? Url { get; init; }
    public string? Category { get; init; }
    public string? Icon { get; init; }
    public string? ImageUrl { get; init; }
    public string? Hostname { get; init; }
    public bool Ignore { get; init; }
    public bool Autogenerated { get; init; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public Service()
    {
    }

    public Service(string name, string? url, string? category, string? icon, string? imageUrl,
                   string? hostname, bool ignore, bool autogenerated = false)
    {
        Name = name;
        Url = url;
        Category = category;
        Icon = icon;
        ImageUrl = imageUrl;
        Hostname = hostname;
        Ignore = ignore;
        Autogenerated = autogenerated;
    }
}
