---
services:
  dashboard-services-manager-api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
  dashboard-services-manager-provider:
    build:
      context: ..
      dockerfile: docker/provider.Dockerfile
