---
ProviderOptions:
  ApiUrl: http://dashboard-services-manager-api:8080
  ServicesProviders:
    - ServicesProviderType: docker
      AreServiceHostsHttps: true
      DockerLabelPrefix: dcm
      Hostname: example-provider
