using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Managers.Services;
using Dsm.Shared.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Dsm.Managers;

public class DashboardCommandProcessor
{
    private readonly ManagerOptions _managerOptions;
    private readonly DashboardManagerFactory _dashboardManagerFactory;
    private readonly ServiceWithDefaultsFactory _serviceWithDefaultsFactory;
    private readonly ServicesCombiner _servicesCombiner;
    private readonly ILogger<DashboardCommandProcessor> _logger;

    public DashboardCommandProcessor(
        IOptions<ManagerOptions> managerOptions,
        DashboardManagerFactory dashboardManagerFactory,
        ServiceWithDefaultsFactory serviceWithDefaultsFactory,
        ServicesCombiner servicesCombiner,
        ILogger<DashboardCommandProcessor> logger)
    {
        _managerOptions = managerOptions.Value;
        _dashboardManagerFactory = dashboardManagerFactory;
        _serviceWithDefaultsFactory = serviceWithDefaultsFactory;
        _servicesCombiner = servicesCombiner;
        _logger = logger;
    }

    public async Task<Dictionary<string, List<Service>>> UpdateWithServicesFromProvider(IEnumerable<Service> providerServices)
    {
        var providerList = providerServices as List<Service> ?? providerServices.ToList();
        var ignoredNames = _managerOptions.IgnoredServiceNames ?? new List<string>();
        var newServicesWithDefaults = providerList
            .Where(s => !s.Ignore &&
                        !string.IsNullOrWhiteSpace(s.Url) &&
                        !ignoredNames.Contains(s.Name, StringComparer.OrdinalIgnoreCase))
            .Select(s => _serviceWithDefaultsFactory.CreateWithDefaults(s with { Autogenerated = true }))
            .ToList();

        _logger.LogDebug(
            "Manager filtered services: {Received} received, {Kept} kept, {Dropped} dropped (ignored/blank/named)",
            providerList.Count, newServicesWithDefaults.Count, providerList.Count - newServicesWithDefaults.Count);

        var results = new Dictionary<string, List<Service>>();
        foreach (var managerConfig in _managerOptions.DashboardManagers)
        {
            var key = managerConfig.DashboardManagerType.ToString();
            var manager = _dashboardManagerFactory.Create(managerConfig);

            var existing = await manager.ListServices();
            _logger.LogDebug("Dashboard '{DashboardManager}' has {Count} existing services: {@Services}",
                manager.Type, existing.Count, existing);

            var combined = _servicesCombiner.CombineExistingServicesWithNewServices(existing, newServicesWithDefaults);
            _logger.LogDebug("Dashboard '{DashboardManager}' will write {Count} services: {@Services}",
                manager.Type, combined.Count, combined);

            var added = combined
                .Where(c => !existing.Any(e => e.Name == c.Name && e.Hostname == c.Hostname))
                .ToList();
            var removed = existing
                .Where(e => !combined.Any(c => c.Name == e.Name && c.Hostname == e.Hostname))
                .ToList();

            _logger.LogDebug(
                "Dashboard '{DashboardManager}' diff: {AddedCount} added [{AddedNames}], {RemovedCount} removed [{RemovedNames}] ({@Added}, {@Removed})",
                manager.Type,
                added.Count, string.Join(", ", added.Select(s => s.Name)),
                removed.Count, string.Join(", ", removed.Select(s => s.Name)),
                added, removed);

            var changed = await manager.WriteServices(combined);
            if (changed)
            {
                _logger.LogInformation(
                    "Dashboard '{DashboardManager}' wrote {Count} services to '{Path}': {AddedCount} added [{AddedNames}], {RemovedCount} removed [{RemovedNames}]",
                    manager.Type, combined.Count, manager.ConfigFilePath,
                    added.Count, string.Join(", ", added.Select(s => s.Name)),
                    removed.Count, string.Join(", ", removed.Select(s => s.Name)));
            }
            else
            {
                _logger.LogDebug("Dashboard '{DashboardManager}' had no changes at '{Path}'",
                    manager.Type, manager.ConfigFilePath);
            }

            results[key] = combined;
        }
        return results;
    }
}
