using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers;
using Dsm.Managers.Services;
using Dsm.Shared.Models;
using Microsoft.Extensions.Options;

namespace Dsm.Managers;

public class DashboardCommandProcessor
{
    private readonly ManagerOptions _managerOptions;
    private readonly DashboardManagerFactory _dashboardManagerFactory;
    private readonly ServiceWithDefaultsFactory _serviceWithDefaultsFactory;
    private readonly ServicesCombiner _servicesCombiner;

    public DashboardCommandProcessor(
        IOptions<ManagerOptions> managerOptions,
        DashboardManagerFactory dashboardManagerFactory,
        ServiceWithDefaultsFactory serviceWithDefaultsFactory,
        ServicesCombiner servicesCombiner)
    {
        _managerOptions = managerOptions.Value;
        _dashboardManagerFactory = dashboardManagerFactory;
        _serviceWithDefaultsFactory = serviceWithDefaultsFactory;
        _servicesCombiner = servicesCombiner;
    }

    public async Task<Dictionary<string, List<Service>>> UpdateWithServicesFromProvider(IEnumerable<Service> providerServices)
    {
        var ignoredNames = _managerOptions.IgnoredServiceNames ?? new List<string>();
        var newServicesWithDefaults = providerServices
            .Where(s => !s.Ignore &&
                        !string.IsNullOrWhiteSpace(s.Url) &&
                        !ignoredNames.Contains(s.Name, StringComparer.OrdinalIgnoreCase))
            .Select(s => _serviceWithDefaultsFactory.CreateWithDefaults(s with { Autogenerated = true }))
            .ToList();

        var results = new Dictionary<string, List<Service>>();
        foreach (var managerConfig in _managerOptions.DashboardManagers)
        {
            var key = managerConfig.DashboardManagerType.ToString();
            var manager = _dashboardManagerFactory.Create(managerConfig);
            var existing = await manager.ListServices();
            var combined = _servicesCombiner.CombineExistingServicesWithNewServices(existing, newServicesWithDefaults);
            await manager.WriteServices(combined);
            results[key] = combined;
        }
        return results;
    }
}
