using System.ComponentModel;
using Dsm.Shared.Models;

namespace Dsm.Managers.DashboardManagers.Dashy;
public class DashyItem
{
    public const string AutogeneratedTag = "_autogenerated";

    public static DashyItem Create(Service service, bool enableStatusMonitoring)
    {
        var dashyIcon =
            !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl :
            !string.IsNullOrEmpty(service.Icon)    ? service.Icon     :
                                                     "favicon-local";
        var tags = new List<string>();
        if (service.Autogenerated)
        {
            tags.Add(AutogeneratedTag);
        }
        if (!string.IsNullOrEmpty(service.Hostname))
        {
            tags.Add($"host={service.Hostname}");
        }

        return new DashyItem(service.Name, service.Url, dashyIcon, tags)
        {
            StatusCheck = enableStatusMonitoring ? true : null
        };
    }

    public DashyItem(string title, string? url, string icon, List<string> tags)
    {
        Title = title;
        Url = url ?? string.Empty;
        Icon = icon;
        Tags = tags;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public DashyItem()
    {
        Title = string.Empty;
        Url = string.Empty;
        Icon = string.Empty;
        Tags = new List<string>();
    }

    public string Title { get; set; }
    public string Url { get; set; }
    public string Icon { get; set; }
    public List<string> Tags { get; set; }
    public bool? StatusCheck { get; set; }
  }