using System.Globalization;
using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers.Dashy;
using Dsm.Managers.Services;
using Dsm.Managers.Services.IconSources;
using Dsm.Shared.Extensions;
using Dsm.Shared.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Dsm.Managers.DashboardManagers;

public class DashyDashboardManager : IDashboardManager
{
    public const string ConfigFileName = "conf.yml";

    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly DashboardManagerConfig _config;
    private readonly IconResolver _iconResolver;
    private readonly ILogger<DashyDashboardManager> _logger;

    public DashyDashboardManager(
        DashboardManagerConfig config,
        IOptions<ServiceDefaultOptions> defaultOptions,
        IconResolver iconResolver,
        ILogger<DashyDashboardManager> logger)
    {
        _serviceDefaultOptions = defaultOptions.Value;
        _config = config;
        _iconResolver = iconResolver;
        _logger = logger;
    }

    public IReadOnlyDictionary<DashboardIconSourceType, string> NativeIconSourcePrefixes { get; }
        = new Dictionary<DashboardIconSourceType, string>
        {
            [DashboardIconSourceType.HomarrLabs] = "hl-",
            [DashboardIconSourceType.SelfhSt] = "sh-",
            [DashboardIconSourceType.MaterialDesignIcons] = "mdi-",
        };

    public DashboardManagerType Type => DashboardManagerType.Dashy;
    public string ConfigFilePath => Path.Combine(_config.DashboardConfigDirectoryPath, ConfigFileName);

    public async Task<List<Service>> ListServices()
    {
        var dashyConfig = await LoadDashyConfig<DashyConfig>();
        var services = new List<Service>();
        foreach (var dashySection in dashyConfig.Sections)
        {
            foreach (var dashyItem in dashySection.Items)
            {
                var (icon, imageUrl) = GetIconOrImageUrl(dashyItem.Icon);
                var tags = dashyItem.Tags ?? [];
                var hostname = GetHostnameFromTags(tags);
                var autogenerated = tags.Contains(DashyItem.AutogeneratedTag);
                var service = new Service(dashyItem.Title, dashyItem.Url, dashySection.Name, icon,
                    imageUrl, hostname, false, autogenerated);
                services.Add(service);
            }
        }

        return services;
    }

    public async Task<bool> WriteServices(List<Service> services)
    {
        var resolvedIcons = new Dictionary<Service, (string? Icon, string? ImageUrl)>();
        foreach (var s in services)
        {
            resolvedIcons[s] = await _iconResolver.Resolve(s, this);
        }

        var sectionIcons = await ResolveSectionIcons(services);
        var dashySections = CreateDashySections(services, resolvedIcons, sectionIcons);

        // Round-trip sections through YAML as `object` so we can merge them into the
        // existing config dictionary while preserving all non-sections top-level keys
        // (appConfig, pageInfo, etc.).
        var serializer = CreateSerializer();
        var deserializer = CreateDeserializer();
        var dashySectionsYaml = serializer.Serialize(dashySections);
        var dashySectionsObject = deserializer.Deserialize<object>(dashySectionsYaml);
        var dashyConfigObject = await LoadDashyConfig<Dictionary<object, object>>();

        if (dashyConfigObject.ContainsKey("sections"))
        {
            dashyConfigObject["sections"] = dashySectionsObject;
        }
        else
        {
            dashyConfigObject.Add("sections", dashySectionsObject);
        }

        var sw = new StringWriter();
        serializer.Serialize(sw, dashyConfigObject);
        return await YamlFileWriter.WriteIfChanged(ConfigFilePath, sw.ToString());
    }

    private static (string? icon, string? imageUrl) GetIconOrImageUrl(string? icon)
    {
        if (string.IsNullOrEmpty(icon)) return (null, null);
        return icon.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? (null, icon) : (icon, null);
    }

    private static string? GetHostnameFromTags(List<string> tags)
    {
        const string prefix = "host=";
        foreach (var tag in tags)
        {
            if (tag.StartsWith(prefix, StringComparison.Ordinal) && tag.Length > prefix.Length)
            {
                return tag.Substring(prefix.Length);
            }
        }

        return null;
    }

    private List<DashySection> CreateDashySections(
        List<Service> services,
        IReadOnlyDictionary<Service, (string? Icon, string? ImageUrl)> resolvedIcons,
        IReadOnlyDictionary<string, string?> sectionIcons)
    {
        var sectionNameToItemsMapping = new Dictionary<string, List<DashyItem>>();
        foreach (var service in services)
        {
            var (icon, imageUrl) = resolvedIcons[service];
            var dashyItem = DashyItem.Create(service, icon, imageUrl, _config.EnableStatusMonitoring);
            sectionNameToItemsMapping.AddToLookup((service.Category ?? string.Empty).ToLowerInvariant(), dashyItem);
        }

        var dashySections = sectionNameToItemsMapping
            .Select(kvp => CreateDashySection(kvp.Key, kvp.Value, sectionIcons))
            .OrderBy(s => s.Name)
            .ToList();
        return dashySections;
    }

    private static DashySection CreateDashySection(
        string name,
        List<DashyItem> dashyItems,
        IReadOnlyDictionary<string, string?> sectionIcons)
    {
        dashyItems = dashyItems.OrderBy(i => i.Title).ToList();

        var dashySectionName = string.IsNullOrEmpty(name)
            ? "Uncategorized"
            : CultureInfo.InvariantCulture.TextInfo.ToTitleCase(name);

        sectionIcons.TryGetValue(dashySectionName, out var sectionIcon);

        return new DashySection(dashySectionName, sectionIcon, dashyItems);
    }

    private async Task<Dictionary<string, string?>> ResolveSectionIcons(List<Service> services)
    {
        // Compute distinct section names (title-cased) the same way CreateDashySection does,
        // then resolve each category's configured icon through IconResolver — prefix
        // translation, native pass-through, CDN probe, all the same as service icons. No
        // fallback chain: a category with no defaults icon stays unset.
        var distinctSectionNames = services
            .Select(s => string.IsNullOrEmpty(s.Category)
                ? "Uncategorized"
                : CultureInfo.InvariantCulture.TextInfo.ToTitleCase(s.Category!.ToLowerInvariant()))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var resolved = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);
        foreach (var sectionName in distinctSectionNames)
        {
            var rawIcon = _serviceDefaultOptions.Categories.TryGetValue(sectionName, out var c)
                ? c.Icon
                : null;
            var (icon, imageUrl) = await _iconResolver.ResolveIcon(rawIcon, this);
            resolved[sectionName] = imageUrl ?? icon;
        }
        return resolved;
    }

    private async Task<T> LoadDashyConfig<T>()
        where T : new()
    {
        if (!File.Exists(ConfigFilePath))
        {
            _logger.LogWarning("Dashy config file '{Path}' does not exist; using empty config.",
                ConfigFilePath);
            return new T();
        }

        var text = await File.ReadAllTextAsync(ConfigFilePath);
        return CreateDeserializer().Deserialize<T>(text) ?? new T();
    }

    private static IDeserializer CreateDeserializer()
    {
        return new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();
    }

    private static ISerializer CreateSerializer()
    {
        return new SerializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }
}