using System.Globalization;
using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers.Dashy;
using Dsm.Shared.Extensions;
using Dsm.Shared.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Dsm.Managers.DashboardManagers;

public class DashyDashboardManager : IDashboardManager
{
    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly DashboardManagerConfig _config;
    private readonly ILogger<DashyDashboardManager> _logger;

    public DashyDashboardManager(
        DashboardManagerConfig config,
        IOptions<ServiceDefaultOptions> defaultOptions,
        ILogger<DashyDashboardManager> logger)
    {
        _serviceDefaultOptions = defaultOptions.Value;
        _config = config;
        _logger = logger;
    }

    public async Task<List<Service>> ListServices()
    {
        var dashyConfig = await LoadDashyConfig<DashyConfig>();
        var services = new List<Service>();
        foreach (var dashySection in dashyConfig.Sections)
        {
            foreach (var dashyItem in dashySection.Items)
            {
                var (icon, imageUrl) = GetIconOrImageUrl(dashyItem.Icon);
                var tags = dashyItem.Tags ?? [];
                var hostname = GetHostnameFromTags(tags);
                var autogenerated = tags.Contains(DashyItem.AutogeneratedTag);
                var service = new Service(dashyItem.Title, dashyItem.Url, dashySection.Name, icon,
                    imageUrl, hostname, false, autogenerated);
                services.Add(service);
            }
        }

        return services;
    }

    public async Task WriteServices(List<Service> services)
    {
        var dashySections = CreateDashySections(services);

        // Round-trip sections through YAML as `object` so we can merge them into the
        // existing config dictionary while preserving all non-sections top-level keys
        // (appConfig, pageInfo, etc.).
        var serializer = CreateSerializer();
        var deserializer = CreateDeserializer();
        var dashySectionsYaml = serializer.Serialize(dashySections);
        var dashySectionsObject = deserializer.Deserialize<object>(dashySectionsYaml);
        var dashyConfigObject = await LoadDashyConfig<Dictionary<object, object>>();

        if (dashyConfigObject.ContainsKey("sections"))
        {
            dashyConfigObject["sections"] = dashySectionsObject;
        }
        else
        {
            dashyConfigObject.Add("sections", dashySectionsObject);
        }

        using (var textWriter = File.CreateText(_config.DashboardConfigFilePath))
        {
            serializer.Serialize(textWriter, dashyConfigObject);
        }
    }

    private static (string? icon, string? imageUrl) GetIconOrImageUrl(string? icon)
    {
        if (string.IsNullOrEmpty(icon)) return (null, null);
        return icon.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? (null, icon) : (icon, null);
    }

    private static string? GetHostnameFromTags(List<string> tags)
    {
        const string prefix = "host=";
        foreach (var tag in tags)
        {
            if (tag.StartsWith(prefix, StringComparison.Ordinal) && tag.Length > prefix.Length)
            {
                return tag.Substring(prefix.Length);
            }
        }

        return null;
    }

    private List<DashySection> CreateDashySections(List<Service> services)
    {
        var sectionNameToItemsMapping = new Dictionary<string, List<DashyItem>>();
        foreach (var service in services)
        {
            var dashyItem = DashyItem.Create(service, _config.EnableStatusMonitoring);
            sectionNameToItemsMapping.AddToLookup((service.Category ?? string.Empty).ToLowerInvariant(), dashyItem);
        }

        var dashySections = sectionNameToItemsMapping
            .Select(kvp => CreateDashySection(kvp.Key, kvp.Value))
            .OrderBy(s => s.Name)
            .ToList();
        return dashySections;
    }

    private DashySection CreateDashySection(string name, List<DashyItem> dashyItems)
    {
        dashyItems = dashyItems.OrderBy(i => i.Title).ToList();
        string? sectionIcon = null;

        var dashySectionName = string.IsNullOrEmpty(name)
            ? "Uncategorized"
            : CultureInfo.InvariantCulture.TextInfo.ToTitleCase(name);

        // Categories uses StringComparer.OrdinalIgnoreCase (see ServiceDefaultOptions),
        // so we look up with the title-cased section name directly.
        if (_serviceDefaultOptions.Categories.TryGetValue(dashySectionName, out var defaultCategoryConfig))
        {
            sectionIcon = defaultCategoryConfig.Icon;
        }

        var dashySection = new DashySection(dashySectionName, sectionIcon, dashyItems);
        return dashySection;
    }

    private async Task<T> LoadDashyConfig<T>()
        where T : new()
    {
        if (!File.Exists(_config.DashboardConfigFilePath))
        {
            _logger.LogWarning("Dashy config file '{Path}' does not exist; using empty config.",
                _config.DashboardConfigFilePath);
            return new T();
        }

        var text = await File.ReadAllTextAsync(_config.DashboardConfigFilePath);
        return CreateDeserializer().Deserialize<T>(text) ?? new T();
    }

    private static IDeserializer CreateDeserializer()
    {
        return new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();
    }

    private static ISerializer CreateSerializer()
    {
        return new SerializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }
}