using System.Globalization;
using System.Text.RegularExpressions;
using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers.Homepage;
using Dsm.Shared.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Dsm.Managers.DashboardManagers;

public class HomepageDashboardManager : IDashboardManager
{
    public const string ServicesFileName = "services.yaml";
    public const string SettingsFileName = "settings.yaml";
    private const string LayoutKey = "layout";
    private const string IconKey = "icon";

    private const string UncategorizedGroup = "Uncategorized";
    private static readonly Regex LetterAfterDigit = new(@"(?<=\d)[a-z]", RegexOptions.Compiled);

    private readonly DashboardManagerConfig _config;
    private readonly ServiceDefaultOptions _serviceDefaultOptions;
    private readonly ILogger<HomepageDashboardManager> _logger;

    public HomepageDashboardManager(
        DashboardManagerConfig config,
        IOptions<ServiceDefaultOptions> defaultOptions,
        ILogger<HomepageDashboardManager> logger)
    {
        _config = config;
        _serviceDefaultOptions = defaultOptions.Value;
        _logger = logger;
    }

    private string ServicesFilePath => Path.Combine(_config.DashboardConfigDirectoryPath, ServicesFileName);
    private string SettingsFilePath => Path.Combine(_config.DashboardConfigDirectoryPath, SettingsFileName);

    public async Task<List<Service>> ListServices()
    {
        var groups = await LoadGroups();
        var services = new List<Service>();
        foreach (var group in groups)
        {
            if (group is null) continue;
            foreach (var (groupName, entries) in group)
            {
                if (entries is null) continue;
                foreach (var entryMap in entries)
                {
                    if (entryMap is null) continue;
                    foreach (var (serviceName, entry) in entryMap)
                    {
                        var (icon, imageUrl) = GetIconOrImageUrl(entry.Icon);
                        services.Add(new Service(
                            serviceName,
                            entry.Href,
                            groupName,
                            icon,
                            imageUrl,
                            entry.Server,
                            false,
                            entry.Autogenerated,
                            entry.ServiceDefaultsName));
                    }
                }
            }
        }
        return services;
    }

    public async Task WriteServices(List<Service> services)
    {
        var widgets = await LoadWidgetEntries();
        var output = services
            .GroupBy(s => string.IsNullOrEmpty(s.Category) ? UncategorizedGroup : TitleCaseCategory(s.Category!))
            .OrderBy(g => g.Key)
            .Select(g => new Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>
            {
                [g.Key] = g.OrderBy(s => s.Name).Select(s => ToEntryMap(s, _config.EnableStatusMonitoring, widgets, _logger)).ToList()
            })
            .ToList();

        var serializer = CreateSerializer();
        var sw = new StringWriter();
        serializer.Serialize(sw, output);
        await YamlFileWriter.WriteIfChanged(ServicesFilePath, sw.ToString());

        await UpdateSettingsLayoutIcons(services);
    }

    private async Task UpdateSettingsLayoutIcons(List<Service> services)
    {
        var groupIcons = services
            .Select(s => string.IsNullOrEmpty(s.Category) ? UncategorizedGroup : TitleCaseCategory(s.Category!))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(name => (Name: name,
                             Icon: _serviceDefaultOptions.Categories.TryGetValue(name, out var c) ? c.Icon : null))
            .Where(p => !string.IsNullOrEmpty(p.Icon))
            .ToList();
        if (groupIcons.Count == 0) return;

        var settings = await LoadSettings();
        var layout = GetOrCreateLayoutMap(settings);

        foreach (var (name, icon) in groupIcons)
        {
            if (layout.TryGetValue(name, out var existing) && existing is IDictionary<object, object> existingMap)
            {
                existingMap[IconKey] = icon!;
            }
            else
            {
                layout[name] = new Dictionary<object, object> { [IconKey] = icon! };
            }
        }

        var serializer = CreateSerializer();
        var sw = new StringWriter();
        serializer.Serialize(sw, settings);
        await YamlFileWriter.WriteIfChanged(SettingsFilePath, sw.ToString());
    }

    private async Task<Dictionary<object, object>> LoadSettings()
    {
        if (!File.Exists(SettingsFilePath))
        {
            return new Dictionary<object, object>();
        }
        var text = await File.ReadAllTextAsync(SettingsFilePath);
        var parsed = CreateDeserializer().Deserialize<Dictionary<object, object>>(text);
        return parsed ?? new Dictionary<object, object>();
    }

    private IDictionary<object, object> GetOrCreateLayoutMap(Dictionary<object, object> settings)
    {
        if (settings.TryGetValue(LayoutKey, out var existing))
        {
            if (existing is IDictionary<object, object> asMap)
            {
                return asMap;
            }
            _logger.LogWarning("Homepage settings.yaml 'layout' was not a map ({Type}); replacing it.",
                existing?.GetType().Name ?? "null");
        }

        var layout = new Dictionary<object, object>();
        settings[LayoutKey] = layout;
        return layout;
    }

    private static string TitleCaseCategory(string category)
    {
        var titled = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(category);
        return LetterAfterDigit.Replace(titled, m => m.Value.ToUpperInvariant());
    }

    private static Dictionary<string, HomepageServiceEntry> ToEntryMap(
        Service service,
        bool enableStatusMonitoring,
        IReadOnlyDictionary<string, List<HomepageServiceWidgetEntry>> widgets,
        ILogger logger)
    {
        var icon = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : service.Icon;
        var w = FindWidget(widgets, service);
        var hasWidget = w is not null && (w.Widgets is { Count: > 0 } || w.Widget is not null);
        var entry = new HomepageServiceEntry
        {
            Href = service.Url,
            Icon = string.IsNullOrEmpty(icon) ? null : icon,
            Server = service.Hostname,
            SiteMonitor = enableStatusMonitoring && !hasWidget ? service.Url : null,
            Autogenerated = service.Autogenerated,
            ServiceDefaultsName = service.ServiceDefaultsName
        };
        if (w is not null)
        {
            if (w.Widgets is { Count: > 0 })
            {
                entry.Widgets = w.Widgets;
                if (w.Widget is not null)
                {
                    logger.LogWarning(
                        "Homepage widget source has both 'widget' and 'widgets' for service '{Name}'; using 'widgets'.",
                        service.Name);
                }
            }
            else if (w.Widget is not null)
            {
                entry.Widget = w.Widget;
            }
        }
        return new Dictionary<string, HomepageServiceEntry> { [service.Name] = entry };
    }

    private static HomepageServiceWidgetEntry? FindWidget(
        IReadOnlyDictionary<string, List<HomepageServiceWidgetEntry>> widgets,
        Service service)
    {
        var names = new List<string>();
        if (!string.IsNullOrEmpty(service.Name)) names.Add(service.Name);
        if (!string.IsNullOrEmpty(service.ServiceDefaultsName) &&
            !string.Equals(service.ServiceDefaultsName, service.Name, StringComparison.OrdinalIgnoreCase))
        {
            names.Add(service.ServiceDefaultsName);
        }

        if (!string.IsNullOrEmpty(service.Hostname))
        {
            foreach (var name in names)
            {
                if (!widgets.TryGetValue(name, out var list)) continue;
                var match = list.FirstOrDefault(e =>
                    string.Equals(e.Server, service.Hostname, StringComparison.OrdinalIgnoreCase));
                if (match is not null) return match;
            }
        }

        foreach (var name in names)
        {
            if (!widgets.TryGetValue(name, out var list)) continue;
            var match = list.FirstOrDefault(e => string.IsNullOrEmpty(e.Server));
            if (match is not null) return match;
        }
        return null;
    }

    private static (string? icon, string? imageUrl) GetIconOrImageUrl(string? icon)
    {
        if (string.IsNullOrEmpty(icon)) return (null, null);
        return icon.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? (null, icon) : (icon, null);
    }

    private async Task<Dictionary<string, List<HomepageServiceWidgetEntry>>> LoadWidgetEntries()
    {
        var result = new Dictionary<string, List<HomepageServiceWidgetEntry>>(StringComparer.OrdinalIgnoreCase);
        var path = _config.SourceHomepageServiceWidgetsFilePath;
        if (string.IsNullOrWhiteSpace(path))
        {
            return result;
        }
        if (!File.Exists(path))
        {
            _logger.LogWarning("Homepage service widgets file '{Path}' does not exist; no widgets will be applied.", path);
            return result;
        }

        var text = await File.ReadAllTextAsync(path);
        var entries = CreateDeserializer()
            .Deserialize<List<Dictionary<string, HomepageServiceWidgetEntry>>>(text);
        if (entries is null)
        {
            return result;
        }

        foreach (var map in entries)
        {
            if (map is null) continue;
            foreach (var (name, entry) in map)
            {
                if (string.IsNullOrWhiteSpace(name) || entry is null) continue;
                if (!result.TryGetValue(name, out var list))
                {
                    list = [];
                    result[name] = list;
                }
                var existing = list.FindIndex(e =>
                    string.Equals(e.Server ?? string.Empty, entry.Server ?? string.Empty,
                                  StringComparison.OrdinalIgnoreCase));
                if (existing >= 0)
                {
                    _logger.LogWarning(
                        "Homepage service widgets file has duplicate entry for service '{Name}' (server '{Server}'); last-wins.",
                        name, entry.Server ?? "<none>");
                    list[existing] = entry;
                }
                else
                {
                    list.Add(entry);
                }
            }
        }
        return result;
    }

    private async Task<List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>> LoadGroups()
    {
        var path = ServicesFilePath;
        if (!File.Exists(path))
        {
            _logger.LogWarning("Homepage config file '{Path}' does not exist; using empty config.", path);
            return new List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>();
        }

        var text = await File.ReadAllTextAsync(path);
        var groups = CreateDeserializer()
            .Deserialize<List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>>(text);
        return groups ?? new List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>();
    }

    private static IDeserializer CreateDeserializer()
    {
        return new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();
    }

    private static ISerializer CreateSerializer()
    {
        return new SerializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }
}
