using YamlDotNet.Serialization;

namespace Dsm.Managers.DashboardManagers.Homepage;
public class HomepageServiceEntry
{
    public const string AUTOGENERATED_KEY = "_autogenerated";

    public string? Href { get; set; }
    public string? Icon { get; set; }
    public string? Description { get; set; }
    public string? Server { get; set; }
    public string? Container { get; set; }

    [YamlMember(Alias = AUTOGENERATED_KEY, ApplyNamingConventions = false)]
    public bool Autogenerated { get; set; }
}
