using YamlDotNet.Serialization;

namespace Dsm.Managers.DashboardManagers.Homepage;
public class HomepageServiceEntry
{
    public const string AutogeneratedKey = "_autogenerated";
    public const string ServiceDefaultsNameKey = "_serviceDefaultsName";

    public string? Href { get; set; }
    public string? Icon { get; set; }
    public string? Description { get; set; }
    public string? Server { get; set; }
    public string? Container { get; set; }
    public string? SiteMonitor { get; set; }
    public Dictionary<string, object?>? Widget { get; set; }
    public List<Dictionary<string, object?>>? Widgets { get; set; }

    [YamlMember(Alias = AutogeneratedKey, ApplyNamingConventions = false)]
    public bool Autogenerated { get; set; }

    [YamlMember(Alias = ServiceDefaultsNameKey, ApplyNamingConventions = false)]
    public string? ServiceDefaultsName { get; set; }
}
