---
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push API Docker images
        uses: docker/build-push-action@v4
        with:
          file: api.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/andyattebery/dashboard-services-manager:api-latest
      - name: Build and push Provider Docker images
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dotnet"
          file: provider.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/andyattebery/dashboard-services-manager:provider-latest
