using System.Text.RegularExpressions;
using Dsm.Managers.Configuration;
using Dsm.Managers.DashboardManagers.Homepage;
using Dsm.Shared.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Dsm.Managers.DashboardManagers;

public class HomepageDashboardManager : IDashboardManager
{
    private const string UncategorizedGroup = "Uncategorized";

    private readonly DashboardManagerConfig _config;

    public HomepageDashboardManager(DashboardManagerConfig config)
    {
        _config = config;
    }

    public async Task<List<Service>> ListServices()
    {
        var groups = await LoadGroups();
        var services = new List<Service>();
        foreach (var group in groups)
        {
            foreach (var (groupName, entries) in group)
            {
                foreach (var entryMap in entries)
                {
                    foreach (var (serviceName, entry) in entryMap)
                    {
                        var (icon, imageUrl) = GetIconOrImageUrl(entry.Icon);
                        services.Add(new Service(
                            serviceName,
                            entry.Href,
                            groupName,
                            icon,
                            imageUrl,
                            entry.Server,
                            false,
                            entry.Autogenerated));
                    }
                }
            }
        }
        return services;
    }

    public async Task WriteServices(List<Service> services)
    {
        var path = _config.DashboardConfigFilePath;
        var existingGroups = File.Exists(path)
            ? await LoadGroups()
            : new List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>();

        var preserved = new List<KeyValuePair<string, List<Dictionary<string, HomepageServiceEntry>>>>();
        foreach (var group in existingGroups)
        {
            foreach (var (groupName, entries) in group)
            {
                var kept = entries
                    .Where(entryMap => entryMap.Values.All(e => !e.Autogenerated))
                    .ToList();
                if (kept.Count > 0)
                {
                    preserved.Add(new KeyValuePair<string, List<Dictionary<string, HomepageServiceEntry>>>(groupName, kept));
                }
            }
        }

        var newEntriesByGroup = services
            .GroupBy(s => string.IsNullOrEmpty(s.Category) ? UncategorizedGroup : s.Category!)
            .ToDictionary(g => g.Key, g => g.OrderBy(s => s.Name).Select(ToEntryMap).ToList());

        var groupOrder = new List<string>();
        var mergedEntries = new Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>();
        foreach (var (groupName, entries) in preserved)
        {
            if (!mergedEntries.ContainsKey(groupName))
            {
                groupOrder.Add(groupName);
                mergedEntries[groupName] = new List<Dictionary<string, HomepageServiceEntry>>();
            }
            mergedEntries[groupName].AddRange(entries);
        }
        foreach (var (groupName, entries) in newEntriesByGroup)
        {
            if (!mergedEntries.ContainsKey(groupName))
            {
                groupOrder.Add(groupName);
                mergedEntries[groupName] = new List<Dictionary<string, HomepageServiceEntry>>();
            }
            mergedEntries[groupName].AddRange(entries);
        }

        var output = groupOrder
            .Where(name => mergedEntries[name].Count > 0)
            .Select(name => new Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>
            {
                [name] = mergedEntries[name]
            })
            .ToList();

        var serializer = CreateSerializer();
        using var textWriter = File.CreateText(path);
        serializer.Serialize(textWriter, output);
    }

    private static Dictionary<string, HomepageServiceEntry> ToEntryMap(Service service)
    {
        var icon = !string.IsNullOrEmpty(service.ImageUrl) ? service.ImageUrl : service.Icon;
        var entry = new HomepageServiceEntry
        {
            Href = service.Url,
            Icon = string.IsNullOrEmpty(icon) ? null : icon,
            Server = service.Hostname,
            Autogenerated = true
        };
        return new Dictionary<string, HomepageServiceEntry> { [service.Name] = entry };
    }

    private static (string? icon, string? imageUrl) GetIconOrImageUrl(string? icon)
    {
        if (string.IsNullOrEmpty(icon)) return (null, null);
        return Regex.IsMatch(icon, @"^http", RegexOptions.IgnoreCase) ? (null, icon) : (icon, null);
    }

    private async Task<List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>> LoadGroups()
    {
        var path = _config.DashboardConfigFilePath;
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"{nameof(DashboardManagerConfig)}.{nameof(DashboardManagerConfig.DashboardConfigFilePath)}: {path} does not exist.");
        }

        var deserializer = CreateDeserializer();
        return await Task.Run(() =>
        {
            using var reader = File.OpenText(path);
            var groups = deserializer
                .Deserialize<List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>>(reader);
            return groups ?? new List<Dictionary<string, List<Dictionary<string, HomepageServiceEntry>>>>();
        });
    }

    private static IDeserializer CreateDeserializer()
    {
        return new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();
    }

    private static ISerializer CreateSerializer()
    {
        return new SerializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }
}
